// Generated by scripts/presentation_identity_codegen.py; do not edit.
export const PRODUCT_NAME: string = "Magican";
export const HOST_APP_NAME: string = "Magican Desktop";
export const ASSISTANT_FALLBACK_NAME: string = "Assistant";
