const BLAKE3 = /^blake3:[0-9a-f]{64}$/;

export interface GeneratedArtifactTexts {
  readonly derivedJson: string;
  readonly generatedTypescript: string;
}

/**
 * Refuse checked-in sentinels and admit only the recognizable output shape of
 * the public `magician app check --write-generated` owner. This is a consumer
 * guard, not a generator and not proof of publication or installation review.
 */
export function assertAuthorizedGeneratedArtifacts(artifacts: GeneratedArtifactTexts): void {
  if (artifacts.generatedTypescript.includes("GENERATION_REQUIRED")
    || artifacts.generatedTypescript.includes("APP_GENERATED_ARTIFACT_AUTHORIZED = false")) {
    throw new Error("generated_artifact_unavailable:run reviewed public app generation");
  }
  let derived: unknown;
  try {
    derived = JSON.parse(artifacts.derivedJson);
  } catch {
    throw new Error("generated_artifact_invalid:derived JSON is malformed");
  }
  if (!isRecord(derived)
    || derived.status === "generation_required"
    || derived.package_name !== "research-planner"
    || typeof derived.schema_version !== "number"
    || !Number.isSafeInteger(derived.schema_version)
    || derived.schema_version < 1
    || typeof derived.manifest_digest !== "string"
    || !BLAKE3.test(derived.manifest_digest)
    || typeof derived.derivation_digest !== "string"
    || !BLAKE3.test(derived.derivation_digest)) {
    throw new Error("generated_artifact_invalid:derived contract is not current owner output");
  }
  if (!artifacts.generatedTypescript.startsWith("// Generated by `magician app check --write-generated`; do not edit.\n")
    || !artifacts.generatedTypescript.includes("export const APP_CONTRACT_VERSION")
    || !artifacts.generatedTypescript.includes("export type AppEntityName")) {
    throw new Error("generated_artifact_invalid:TypeScript contract is not current owner output");
  }
}

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
