// Generated by scripts/presentation_identity_codegen.py; do not edit.
enum ProductIdentity {
    static let productName = "Magican"
    static let hostAppName = "Magican Desktop"
    static let assistantFallbackName = "Assistant"
}
