// @generated by magician/examples/thinking_map_wire_fixtures.rs — do not edit.
//
// Raw JSON constants for the LTM wire fixtures, one per `Fixtures/<name>.json`.
// The XCTests decode these directly (no bundle-resource loading). Regenerate via:
//   CARGO_TARGET_DIR=/Volumes/build/magician/builds \
//     cargo run -p magician --example thinking_map_wire_fixtures

enum LTMWireFixtures {
    static let mapJSON = #"""
{
  "schema_version": 1,
  "map_id": "map-1",
  "principal": "anonymous",
  "workspace": "default",
  "title": "iOS thinking map migration",
  "source": {
    "kind": "meeting",
    "thread_id": "thread-42"
  },
  "lifecycle": "active",
  "revision": 4,
  "view_state": {
    "active_node": "node-1",
    "lens": "outline"
  },
  "nodes": {
    "node-1": {
      "node_id": "node-1",
      "kind": "decision",
      "label": "Ship the iOS thinking map",
      "detail_markdown": "**Decide** to ship v1 on iOS.",
      "epistemic_state": "asserted",
      "assertion_origin": "owner_spoken",
      "confidence": 0.9,
      "speaker": {
        "speaker_id": "speaker-owner",
        "display_name": "Alex"
      },
      "source_refs": [
        {
          "utterance_id": "utterance-1",
          "thread_id": "thread-42",
          "quote": "Let's ship the iOS thinking map.",
          "timestamp": "2026-07-20T00:00:00Z"
        }
      ],
      "position": {
        "x": 120.0,
        "y": 48.5
      },
      "position_locked": true,
      "promoted_refs": [
        {
          "destination_kind": "task",
          "object_id": "task-1",
          "linked_at": "2026-07-20T00:00:00Z"
        }
      ],
      "tombstoned": false,
      "created_at": "2026-07-20T00:00:00Z",
      "updated_at": "2026-07-20T00:00:00Z"
    },
    "node-2": {
      "node_id": "node-2",
      "kind": "risk",
      "label": "Wire contract drift between Rust and Swift",
      "epistemic_state": "provisional",
      "assertion_origin": "model_inferred",
      "confidence": 0.4,
      "source_refs": [
        {
          "utterance_id": "utterance-2",
          "quote": "the field names could diverge",
          "timestamp": "2026-07-20T00:00:00Z"
        }
      ],
      "parent_id": "node-1",
      "position_locked": false,
      "promoted_refs": [],
      "tombstoned": false,
      "created_at": "2026-07-20T00:00:00Z",
      "updated_at": "2026-07-20T00:00:00Z"
    }
  },
  "edges": {
    "edge-1": {
      "edge_id": "edge-1",
      "from_node": "node-1",
      "to_node": "node-2",
      "kind": "related_to",
      "assertion_origin": "model_inferred",
      "tombstoned": false,
      "created_at": "2026-07-20T00:00:00Z",
      "updated_at": "2026-07-20T00:00:00Z"
    }
  },
  "clarifications": {
    "clar-1": {
      "clarification_id": "clar-1",
      "node_id": "node-2",
      "question": "Which fields are most likely to drift?",
      "state": "open",
      "created_at": "2026-07-20T00:00:00Z"
    }
  },
  "proposals": {},
  "applied_envelopes": [
    {
      "envelope_id": "envelope-1",
      "idempotency_key": "idem-1",
      "resulting_revision": 4
    }
  ],
  "created_at": "2026-07-20T00:00:00Z",
  "updated_at": "2026-07-20T01:00:00Z"
}
"""#

    static let envelopeJSON = #"""
{
  "schema_version": 1,
  "envelope_id": "envelope-1",
  "map_id": "map-1",
  "base_revision": 4,
  "utterance_id": "utterance-3",
  "actor": {
    "actor": "owner",
    "principal": "anonymous"
  },
  "idempotency_key": "idem-1",
  "operations": [
    {
      "op": "add_node",
      "node": {
        "node_id": "node-2",
        "kind": "risk",
        "label": "Wire contract drift between Rust and Swift",
        "epistemic_state": "provisional",
        "assertion_origin": "model_inferred",
        "confidence": 0.4,
        "source_refs": [
          {
            "utterance_id": "utterance-2",
            "quote": "the field names could diverge",
            "timestamp": "2026-07-20T00:00:00Z"
          }
        ],
        "parent_id": "node-1",
        "position_locked": false,
        "promoted_refs": [],
        "tombstoned": false,
        "created_at": "2026-07-20T00:00:00Z",
        "updated_at": "2026-07-20T00:00:00Z"
      }
    },
    {
      "op": "update_node",
      "node_id": "node-1",
      "label": "Ship the iOS thinking map (v1)",
      "detail_markdown": "Updated detail body.",
      "confidence": 0.95
    },
    {
      "op": "set_node_kind",
      "node_id": "node-2",
      "kind": "assumption"
    },
    {
      "op": "set_epistemic_state",
      "node_id": "node-2",
      "state": "confirmed"
    },
    {
      "op": "connect",
      "edge": {
        "edge_id": "edge-1",
        "from_node": "node-1",
        "to_node": "node-2",
        "kind": "related_to",
        "assertion_origin": "model_inferred",
        "tombstoned": false,
        "created_at": "2026-07-20T00:00:00Z",
        "updated_at": "2026-07-20T00:00:00Z"
      }
    },
    {
      "op": "move_to_parent",
      "node_id": "node-2",
      "parent_id": "node-1"
    },
    {
      "op": "tombstone_node",
      "node_id": "node-2"
    },
    {
      "op": "create_clarification",
      "clarification": {
        "clarification_id": "clar-1",
        "node_id": "node-2",
        "question": "Which fields are most likely to drift?",
        "state": "open",
        "created_at": "2026-07-20T00:00:00Z"
      }
    },
    {
      "op": "set_title",
      "title": "iOS thinking map migration (renamed)"
    },
    {
      "op": "set_lifecycle",
      "lifecycle": "archived"
    }
  ],
  "model_trace": {
    "trace_id": "trace-1",
    "model_profile": "thinking_map_interpret"
  },
  "created_at": "2026-07-20T00:00:00Z"
}
"""#

    /// Back-compat shape: an OLD server that never emits `node_preview`. Decoding
    /// this must still succeed with `nodePreview == nil`.
    static let summaryJSON = #"""
{
  "map_id": "map-1",
  "title": "iOS thinking map migration",
  "lifecycle": "active",
  "latest_revision": 4,
  "updated_at": "2026-07-20T01:00:00Z"
}
"""#

    /// New shape: a server that DOES emit the bounded `node_preview` (two nodes,
    /// one branch edge). Mirrors the Rust `MapSummary`/`NodePreview` wire contract.
    static let summaryWithPreviewJSON = #"""
{
  "map_id": "map-1",
  "title": "iOS thinking map migration",
  "lifecycle": "active",
  "latest_revision": 4,
  "updated_at": "2026-07-20T01:00:00Z",
  "node_preview": {
    "nodes": [
      {
        "node_id": "11111111-1111-1111-1111-111111111111",
        "kind": "idea",
        "suggested": false,
        "title": "Root idea"
      },
      {
        "node_id": "22222222-2222-2222-2222-222222222222",
        "parent_id": "11111111-1111-1111-1111-111111111111",
        "kind": "question",
        "suggested": true,
        "title": "Open question"
      }
    ],
    "edges": [
      {
        "from": "11111111-1111-1111-1111-111111111111",
        "to": "22222222-2222-2222-2222-222222222222"
      }
    ]
  }
}
"""#

    static let eventJSON = #"""
{
  "sequence": 1,
  "envelope": {
    "schema_version": 1,
    "envelope_id": "envelope-1",
    "map_id": "map-1",
    "base_revision": 4,
    "utterance_id": "utterance-3",
    "actor": {
      "actor": "owner",
      "principal": "anonymous"
    },
    "idempotency_key": "idem-1",
    "operations": [
      {
        "op": "add_node",
        "node": {
          "node_id": "node-2",
          "kind": "risk",
          "label": "Wire contract drift between Rust and Swift",
          "epistemic_state": "provisional",
          "assertion_origin": "model_inferred",
          "confidence": 0.4,
          "source_refs": [
            {
              "utterance_id": "utterance-2",
              "quote": "the field names could diverge",
              "timestamp": "2026-07-20T00:00:00Z"
            }
          ],
          "parent_id": "node-1",
          "position_locked": false,
          "promoted_refs": [],
          "tombstoned": false,
          "created_at": "2026-07-20T00:00:00Z",
          "updated_at": "2026-07-20T00:00:00Z"
        }
      },
      {
        "op": "update_node",
        "node_id": "node-1",
        "label": "Ship the iOS thinking map (v1)",
        "detail_markdown": "Updated detail body.",
        "confidence": 0.95
      },
      {
        "op": "set_node_kind",
        "node_id": "node-2",
        "kind": "assumption"
      },
      {
        "op": "set_epistemic_state",
        "node_id": "node-2",
        "state": "confirmed"
      },
      {
        "op": "connect",
        "edge": {
          "edge_id": "edge-1",
          "from_node": "node-1",
          "to_node": "node-2",
          "kind": "related_to",
          "assertion_origin": "model_inferred",
          "tombstoned": false,
          "created_at": "2026-07-20T00:00:00Z",
          "updated_at": "2026-07-20T00:00:00Z"
        }
      },
      {
        "op": "move_to_parent",
        "node_id": "node-2",
        "parent_id": "node-1"
      },
      {
        "op": "tombstone_node",
        "node_id": "node-2"
      },
      {
        "op": "create_clarification",
        "clarification": {
          "clarification_id": "clar-1",
          "node_id": "node-2",
          "question": "Which fields are most likely to drift?",
          "state": "open",
          "created_at": "2026-07-20T00:00:00Z"
        }
      },
      {
        "op": "set_title",
        "title": "iOS thinking map migration (renamed)"
      },
      {
        "op": "set_lifecycle",
        "lifecycle": "archived"
      }
    ],
    "model_trace": {
      "trace_id": "trace-1",
      "model_profile": "thinking_map_interpret"
    },
    "created_at": "2026-07-20T00:00:00Z"
  },
  "resulting_revision": 4,
  "semantic_hash": "sha256:deadbeefcafef00d",
  "applied_at": "2026-07-20T01:00:00Z"
}
"""#

    static let manifestJSON = #"""
{
  "schema_version": 1,
  "map_id": "map-1",
  "principal": "anonymous",
  "workspace": "default",
  "title": "iOS thinking map migration",
  "source": {
    "kind": "meeting",
    "thread_id": "thread-42"
  },
  "lifecycle": "active",
  "latest_revision": 4,
  "latest_sequence": 1,
  "latest_semantic_hash": "sha256:deadbeefcafef00d",
  "created_at": "2026-07-20T00:00:00Z",
  "updated_at": "2026-07-20T01:00:00Z"
}
"""#

    static let responseAppliedJSON = #"""
{
  "map": {
    "applied_envelopes": [
      {
        "envelope_id": "envelope-1",
        "idempotency_key": "idem-1",
        "resulting_revision": 4
      }
    ],
    "clarifications": {
      "clar-1": {
        "clarification_id": "clar-1",
        "created_at": "2026-07-20T00:00:00Z",
        "node_id": "node-2",
        "question": "Which fields are most likely to drift?",
        "state": "open"
      }
    },
    "created_at": "2026-07-20T00:00:00Z",
    "edges": {
      "edge-1": {
        "assertion_origin": "model_inferred",
        "created_at": "2026-07-20T00:00:00Z",
        "edge_id": "edge-1",
        "from_node": "node-1",
        "kind": "related_to",
        "to_node": "node-2",
        "tombstoned": false,
        "updated_at": "2026-07-20T00:00:00Z"
      }
    },
    "lifecycle": "active",
    "map_id": "map-1",
    "nodes": {
      "node-1": {
        "assertion_origin": "owner_spoken",
        "confidence": 0.8999999761581421,
        "created_at": "2026-07-20T00:00:00Z",
        "detail_markdown": "**Decide** to ship v1 on iOS.",
        "epistemic_state": "asserted",
        "kind": "decision",
        "label": "Ship the iOS thinking map",
        "node_id": "node-1",
        "position": {
          "x": 120.0,
          "y": 48.5
        },
        "position_locked": true,
        "promoted_refs": [
          {
            "destination_kind": "task",
            "linked_at": "2026-07-20T00:00:00Z",
            "object_id": "task-1"
          }
        ],
        "source_refs": [
          {
            "quote": "Let's ship the iOS thinking map.",
            "thread_id": "thread-42",
            "timestamp": "2026-07-20T00:00:00Z",
            "utterance_id": "utterance-1"
          }
        ],
        "speaker": {
          "display_name": "Alex",
          "speaker_id": "speaker-owner"
        },
        "tombstoned": false,
        "updated_at": "2026-07-20T00:00:00Z"
      },
      "node-2": {
        "assertion_origin": "model_inferred",
        "confidence": 0.4000000059604645,
        "created_at": "2026-07-20T00:00:00Z",
        "epistemic_state": "provisional",
        "kind": "risk",
        "label": "Wire contract drift between Rust and Swift",
        "node_id": "node-2",
        "parent_id": "node-1",
        "position_locked": false,
        "promoted_refs": [],
        "source_refs": [
          {
            "quote": "the field names could diverge",
            "timestamp": "2026-07-20T00:00:00Z",
            "utterance_id": "utterance-2"
          }
        ],
        "tombstoned": false,
        "updated_at": "2026-07-20T00:00:00Z"
      }
    },
    "principal": "anonymous",
    "proposals": {},
    "revision": 4,
    "schema_version": 1,
    "source": {
      "kind": "meeting",
      "thread_id": "thread-42"
    },
    "title": "iOS thinking map migration",
    "updated_at": "2026-07-20T01:00:00Z",
    "view_state": {
      "active_node": "node-1",
      "lens": "outline"
    },
    "workspace": "default"
  },
  "outcome": "applied",
  "resulting_revision": 5,
  "semantic_hash": "sha256:deadbeefcafef00d"
}
"""#

    static let responseIdempotentJSON = #"""
{
  "outcome": "idempotent_replay",
  "resulting_revision": 4
}
"""#

    static let responseNoOperationsJSON = #"""
{
  "outcome": "no_operations"
}
"""#

}
