//! Call-scoped local user transcription for backend-proxied realtime voice.
//!
//! The realtime model continues to receive the original 24 kHz PCM stream. This
//! adapter tees the same frames into the canonical `hands_free` streaming-STT
//! profile, which provides the configured FluidAudio → macOS Speech → cloud
//! fallback chain. It emits display-only partials and finalized user turns; it
//! never feeds text back into the realtime model.

use std::collections::HashSet;
use std::fmt;
use std::sync::atomic::{AtomicU64, AtomicUsize, Ordering};
use std::sync::Arc;
use std::sync::RwLock;

use bytes::Bytes;
use tokio::sync::{mpsc, oneshot};
use tracing::{debug, warn};

use super::{
    resolve_installed_surface_streaming_stt_pipeline, AudioChunk, AudioSurface, StreamAudioFormat,
    StreamSampleFormat, StreamingSttEvent, StreamingSttProvider, StreamingSttSession,
};

const COMMAND_CAPACITY: usize = 256;
const EVENT_CAPACITY: usize = 64;
const REALTIME_PCM_RATE_HZ: u32 = 24_000;
const MAX_QUEUED_AUDIO_BYTES: usize = 1024 * 1024;

#[derive(Debug)]
enum LocalTranscriptCommand {
    Audio(Vec<u8>),
    Boundary {
        next_generation: u64,
        committed: bool,
    },
    End,
}

enum ForwardControl {
    Drain(oneshot::Sender<()>),
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LocalRealtimeTranscriptEvent {
    Partial {
        text: String,
        stream_generation: u64,
    },
    Final {
        text: String,
        stream_generation: u64,
    },
    /// Every provider event generated by `finish()` has been forwarded. The
    /// caller can now commit the corresponding provider input buffer without
    /// racing ahead of the local final transcript.
    CommitReady { stream_generation: u64 },
    Error {
        reason: String,
        stream_generation: u64,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LocalRealtimeTranscriptCommandError {
    QueueFull,
    Closed,
}

impl fmt::Display for LocalRealtimeTranscriptCommandError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::QueueFull => "local realtime transcript command queue is full",
            Self::Closed => "local realtime transcript command queue is closed",
        })
    }
}

fn command_error<T>(error: mpsc::error::TrySendError<T>) -> LocalRealtimeTranscriptCommandError {
    match error {
        mpsc::error::TrySendError::Full(_) => LocalRealtimeTranscriptCommandError::QueueFull,
        mpsc::error::TrySendError::Closed(_) => LocalRealtimeTranscriptCommandError::Closed,
    }
}

/// Non-blocking actor-facing handle. WebSocket ordering is preserved because
/// audio frames and turn controls are inserted synchronously into one bounded
/// command channel.
#[derive(Clone)]
pub struct LocalRealtimeTranscriptHandle {
    commands: mpsc::Sender<LocalTranscriptCommand>,
    profile_id: Arc<str>,
    next_stream_generation: Arc<AtomicU64>,
    suppressed_event_generations: Arc<RwLock<HashSet<u64>>>,
    queued_audio_bytes: Arc<AtomicUsize>,
    queued_audio_frames: Arc<AtomicUsize>,
    queue_high_water_bytes: Arc<AtomicUsize>,
    dropped_audio_frames: Arc<AtomicU64>,
}

impl LocalRealtimeTranscriptHandle {
    pub fn profile_id(&self) -> &str {
        &self.profile_id
    }

    pub fn try_push_audio(&self, pcm: Vec<u8>) -> Result<(), LocalRealtimeTranscriptCommandError> {
        let bytes = pcm.len();
        let queued = loop {
            let current = self.queued_audio_bytes.load(Ordering::Acquire);
            let Some(next) = current.checked_add(bytes) else {
                self.dropped_audio_frames.fetch_add(1, Ordering::AcqRel);
                return Err(LocalRealtimeTranscriptCommandError::QueueFull);
            };
            if next > MAX_QUEUED_AUDIO_BYTES {
                self.dropped_audio_frames.fetch_add(1, Ordering::AcqRel);
                return Err(LocalRealtimeTranscriptCommandError::QueueFull);
            }
            match self.queued_audio_bytes.compare_exchange_weak(
                current,
                next,
                Ordering::AcqRel,
                Ordering::Acquire,
            ) {
                Ok(_) => break next,
                Err(_) => continue,
            }
        };
        self.queued_audio_frames.fetch_add(1, Ordering::AcqRel);
        if let Err(error) = self.commands.try_send(LocalTranscriptCommand::Audio(pcm)) {
            self.queued_audio_bytes.fetch_sub(bytes, Ordering::AcqRel);
            self.queued_audio_frames.fetch_sub(1, Ordering::AcqRel);
            self.dropped_audio_frames.fetch_add(1, Ordering::AcqRel);
            return Err(command_error(error));
        }
        self.queue_high_water_bytes
            .fetch_max(queued, Ordering::AcqRel);
        Ok(())
    }

    pub fn try_commit(&self) -> Result<u64, LocalRealtimeTranscriptCommandError> {
        let current_generation = self.next_stream_generation.fetch_add(1, Ordering::AcqRel);
        let next_generation = current_generation.saturating_add(1);
        if let Err(error) = self.commands.try_send(LocalTranscriptCommand::Boundary {
            next_generation,
            committed: true,
        }) {
            let _ = self.next_stream_generation.compare_exchange(
                next_generation,
                current_generation,
                Ordering::AcqRel,
                Ordering::Acquire,
            );
            return Err(command_error(error));
        }
        Ok(current_generation)
    }

    pub fn try_clear(&self) -> Result<u64, LocalRealtimeTranscriptCommandError> {
        let cleared_generation = self.next_stream_generation.fetch_add(1, Ordering::AcqRel);
        let next_generation = cleared_generation.saturating_add(1);
        if let Ok(mut suppressed) = self.suppressed_event_generations.write() {
            suppressed.insert(cleared_generation);
        }
        if let Err(error) = self.commands.try_send(LocalTranscriptCommand::Boundary {
            next_generation,
            committed: false,
        }) {
            if let Ok(mut suppressed) = self.suppressed_event_generations.write() {
                suppressed.remove(&cleared_generation);
            }
            let _ = self.next_stream_generation.compare_exchange(
                next_generation,
                cleared_generation,
                Ordering::AcqRel,
                Ordering::Acquire,
            );
            return Err(command_error(error));
        }
        Ok(cleared_generation)
    }

    pub fn try_end(&self) -> Result<(), LocalRealtimeTranscriptCommandError> {
        let current_generation = self.next_stream_generation.load(Ordering::Acquire);
        if let Ok(mut suppressed) = self.suppressed_event_generations.write() {
            suppressed.insert(current_generation);
        }
        if let Err(error) = self.commands.try_send(LocalTranscriptCommand::End) {
            if let Ok(mut suppressed) = self.suppressed_event_generations.write() {
                suppressed.remove(&current_generation);
            }
            return Err(command_error(error));
        }
        Ok(())
    }

    pub fn current_stream_generation(&self) -> u64 {
        self.next_stream_generation.load(Ordering::Acquire)
    }

    pub fn queue_snapshot(&self) -> LocalRealtimeTranscriptQueueSnapshot {
        LocalRealtimeTranscriptQueueSnapshot {
            queued_audio_bytes: self.queued_audio_bytes.load(Ordering::Acquire),
            queued_audio_frames: self.queued_audio_frames.load(Ordering::Acquire),
            high_water_audio_bytes: self.queue_high_water_bytes.load(Ordering::Acquire),
            dropped_audio_frames: self.dropped_audio_frames.load(Ordering::Acquire),
        }
    }
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct LocalRealtimeTranscriptQueueSnapshot {
    pub queued_audio_bytes: usize,
    pub queued_audio_frames: usize,
    pub high_water_audio_bytes: usize,
    pub dropped_audio_frames: u64,
}

/// Open a transcript stream for one realtime voice call using the configured
/// hands-free STT profile. Diarization is intentionally disabled: this stream
/// contains only the local user's microphone audio.
pub async fn start_local_realtime_transcript(
    principal: String,
    workspace: String,
    voice_session_id: String,
) -> Result<
    (
        LocalRealtimeTranscriptHandle,
        mpsc::Receiver<LocalRealtimeTranscriptEvent>,
    ),
    String,
> {
    let (pipeline, profile) = resolve_installed_surface_streaming_stt_pipeline(
        AudioSurface::HandsFree,
        Some((principal, workspace)),
        Some(voice_session_id),
    )
    .await?;
    start_with_pipeline(pipeline, profile.profile_id).await
}

async fn start_with_pipeline(
    pipeline: Arc<dyn StreamingSttProvider>,
    profile_id: String,
) -> Result<
    (
        LocalRealtimeTranscriptHandle,
        mpsc::Receiver<LocalRealtimeTranscriptEvent>,
    ),
    String,
> {
    let format = StreamAudioFormat {
        sample_rate_hz: REALTIME_PCM_RATE_HZ,
        channels: 1,
        sample_format: StreamSampleFormat::PcmS16Le,
    };
    let (provider_events_tx, provider_events_rx) = mpsc::channel(EVENT_CAPACITY);
    let session = pipeline
        .open_session(format, provider_events_tx.clone())
        .await
        .map_err(|error| format!("opening local realtime transcript: {error}"))?;
    let (commands_tx, commands_rx) = mpsc::channel(COMMAND_CAPACITY);
    let (events_tx, events_rx) = mpsc::channel(EVENT_CAPACITY);
    let next_stream_generation = Arc::new(AtomicU64::new(1));
    let suppressed_event_generations = Arc::new(RwLock::new(HashSet::new()));
    let queued_audio_bytes = Arc::new(AtomicUsize::new(0));
    let queued_audio_frames = Arc::new(AtomicUsize::new(0));
    let queue_high_water_bytes = Arc::new(AtomicUsize::new(0));
    let dropped_audio_frames = Arc::new(AtomicU64::new(0));

    let forward_control = spawn_forward_events(
        provider_events_rx,
        events_tx.clone(),
        Arc::clone(&suppressed_event_generations),
        1,
    );
    tokio::spawn(run_commands(
        pipeline,
        format,
        session,
        commands_rx,
        events_tx,
        Arc::clone(&suppressed_event_generations),
        Arc::clone(&queued_audio_bytes),
        Arc::clone(&queued_audio_frames),
        Arc::clone(&dropped_audio_frames),
        forward_control,
    ));

    Ok((
        LocalRealtimeTranscriptHandle {
            commands: commands_tx,
            profile_id: Arc::from(profile_id),
            next_stream_generation,
            suppressed_event_generations,
            queued_audio_bytes,
            queued_audio_frames,
            queue_high_water_bytes,
            dropped_audio_frames,
        },
        events_rx,
    ))
}

fn spawn_forward_events(
    provider_events: mpsc::Receiver<StreamingSttEvent>,
    events: mpsc::Sender<LocalRealtimeTranscriptEvent>,
    suppressed_event_generations: Arc<RwLock<HashSet<u64>>>,
    stream_generation: u64,
) -> mpsc::Sender<ForwardControl> {
    let (control_tx, control_rx) = mpsc::channel(1);
    tokio::spawn(forward_events(
        provider_events,
        control_rx,
        events,
        suppressed_event_generations,
        stream_generation,
    ));
    control_tx
}

async fn forward_events(
    mut provider_events: mpsc::Receiver<StreamingSttEvent>,
    mut controls: mpsc::Receiver<ForwardControl>,
    events: mpsc::Sender<LocalRealtimeTranscriptEvent>,
    suppressed_event_generations: Arc<RwLock<HashSet<u64>>>,
    stream_generation: u64,
) {
    loop {
        tokio::select! {
            biased;
            control = controls.recv() => {
                let Some(ForwardControl::Drain(ack)) = control else { break };
                while let Ok(event) = provider_events.try_recv() {
                    if !forward_event(
                        event,
                        &events,
                        &suppressed_event_generations,
                        stream_generation,
                    ).await {
                        break;
                    }
                }
                let _ = ack.send(());
                break;
            },
            event = provider_events.recv() => {
                let Some(event) = event else { break };
                if !forward_event(
                    event,
                    &events,
                    &suppressed_event_generations,
                    stream_generation,
                ).await {
                    break;
                }
            },
        }
    }
}

async fn forward_event(
    event: StreamingSttEvent,
    events: &mpsc::Sender<LocalRealtimeTranscriptEvent>,
    suppressed_event_generations: &RwLock<HashSet<u64>>,
    stream_generation: u64,
) -> bool {
    if suppressed_event_generations
        .read()
        .is_ok_and(|suppressed| suppressed.contains(&stream_generation))
    {
        return true;
    }
    let event = match event {
        StreamingSttEvent::Partial { text, .. } if !text.trim().is_empty() => {
            LocalRealtimeTranscriptEvent::Partial {
                text: text.trim().to_string(),
                stream_generation,
            }
        },
        StreamingSttEvent::Final { text, .. } if !text.trim().is_empty() => {
            LocalRealtimeTranscriptEvent::Final {
                text: text.trim().to_string(),
                stream_generation,
            }
        },
        StreamingSttEvent::Error { reason } => LocalRealtimeTranscriptEvent::Error {
            reason,
            stream_generation,
        },
        _ => return true,
    };
    events.send(event).await.is_ok()
}

async fn run_commands(
    pipeline: Arc<dyn StreamingSttProvider>,
    format: StreamAudioFormat,
    mut session: Box<dyn StreamingSttSession>,
    mut commands: mpsc::Receiver<LocalTranscriptCommand>,
    events: mpsc::Sender<LocalRealtimeTranscriptEvent>,
    suppressed_event_generations: Arc<RwLock<HashSet<u64>>>,
    queued_audio_bytes: Arc<AtomicUsize>,
    queued_audio_frames: Arc<AtomicUsize>,
    dropped_audio_frames: Arc<AtomicU64>,
    mut forward_control: mpsc::Sender<ForwardControl>,
) {
    let mut seq = 0_u64;
    let mut stream_generation = 1_u64;
    let mut session_finished = false;
    while let Some(command) = commands.recv().await {
        match command {
            LocalTranscriptCommand::Audio(pcm) => {
                queued_audio_bytes.fetch_sub(pcm.len(), Ordering::AcqRel);
                queued_audio_frames.fetch_sub(1, Ordering::AcqRel);
                seq = seq.saturating_add(1);
                if let Err(error) = session
                    .push_audio(AudioChunk {
                        seq,
                        pcm: Bytes::from(pcm),
                    })
                    .await
                {
                    let reason = format!("local realtime transcript input failed: {error}");
                    dropped_audio_frames.fetch_add(1, Ordering::AcqRel);
                    discard_queued_audio(
                        &mut commands,
                        &queued_audio_bytes,
                        &queued_audio_frames,
                        &dropped_audio_frames,
                    );
                    let _ = events
                        .send(LocalRealtimeTranscriptEvent::Error {
                            reason,
                            stream_generation,
                        })
                        .await;
                    break;
                }
            },
            LocalTranscriptCommand::Boundary {
                next_generation,
                committed,
            } => {
                let completed_generation = stream_generation;
                if let Err(error) = session.finish().await {
                    let reason = format!("local realtime transcript commit failed: {error}");
                    discard_queued_audio(
                        &mut commands,
                        &queued_audio_bytes,
                        &queued_audio_frames,
                        &dropped_audio_frames,
                    );
                    let _ = events
                        .send(LocalRealtimeTranscriptEvent::Error {
                            reason,
                            stream_generation,
                        })
                        .await;
                    break;
                }
                let (drained_tx, drained_rx) = oneshot::channel();
                if forward_control
                    .send(ForwardControl::Drain(drained_tx))
                    .await
                    .is_err()
                    || drained_rx.await.is_err()
                {
                    discard_queued_audio(
                        &mut commands,
                        &queued_audio_bytes,
                        &queued_audio_frames,
                        &dropped_audio_frames,
                    );
                    let _ = events
                        .send(LocalRealtimeTranscriptEvent::Error {
                            reason: "local realtime transcript event drain failed".to_string(),
                            stream_generation,
                        })
                        .await;
                    break;
                }
                if let Ok(mut suppressed) = suppressed_event_generations.write() {
                    suppressed.remove(&stream_generation);
                }
                let (provider_events, provider_events_rx) = mpsc::channel(EVENT_CAPACITY);
                match pipeline.open_session(format, provider_events).await {
                    Ok(next) => {
                        session = next;
                        seq = 0;
                        stream_generation = next_generation;
                        forward_control = spawn_forward_events(
                            provider_events_rx,
                            events.clone(),
                            Arc::clone(&suppressed_event_generations),
                            stream_generation,
                        );
                        if committed
                            && events
                                .send(LocalRealtimeTranscriptEvent::CommitReady {
                                    stream_generation: completed_generation,
                                })
                                .await
                                .is_err()
                        {
                            break;
                        }
                    },
                    Err(error) => {
                        let reason = format!("local realtime transcript restart failed: {error}");
                        discard_queued_audio(
                            &mut commands,
                            &queued_audio_bytes,
                            &queued_audio_frames,
                            &dropped_audio_frames,
                        );
                        let _ = events
                            .send(LocalRealtimeTranscriptEvent::Error {
                                reason,
                                stream_generation,
                            })
                            .await;
                        break;
                    },
                }
            },
            LocalTranscriptCommand::End => {
                if let Err(error) = session.finish().await {
                    debug!(error = %error, "local realtime transcript final flush failed");
                }
                session_finished = true;
                break;
            },
        }
    }

    // Prevent a sender racing teardown from adding audio after the final drain.
    // `close` preserves already-queued commands so they can still be accounted.
    commands.close();
    discard_queued_audio(
        &mut commands,
        &queued_audio_bytes,
        &queued_audio_frames,
        &dropped_audio_frames,
    );
    if !session_finished {
        if let Err(error) = session.finish().await {
            warn!(error = %error, "local realtime transcript teardown failed");
        }
    }
}

fn discard_queued_audio(
    commands: &mut mpsc::Receiver<LocalTranscriptCommand>,
    queued_audio_bytes: &AtomicUsize,
    queued_audio_frames: &AtomicUsize,
    dropped_audio_frames: &AtomicU64,
) {
    while let Ok(command) = commands.try_recv() {
        if let LocalTranscriptCommand::Audio(pcm) = command {
            queued_audio_bytes.fetch_sub(pcm.len(), Ordering::AcqRel);
            queued_audio_frames.fetch_sub(1, Ordering::AcqRel);
            dropped_audio_frames.fetch_add(1, Ordering::AcqRel);
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::atomic::{AtomicUsize, Ordering};

    use async_trait::async_trait;
    use tokio::sync::{mpsc, Mutex};

    use super::*;
    use crate::media_rails::{StreamingSttCapabilities, SttError};

    struct RecordingProvider {
        opens: Arc<AtomicUsize>,
        chunks: Arc<Mutex<Vec<Vec<u8>>>>,
    }

    #[async_trait]
    impl StreamingSttProvider for RecordingProvider {
        fn id(&self) -> &str {
            "recording"
        }

        fn capabilities(&self) -> StreamingSttCapabilities {
            StreamingSttCapabilities {
                partial_results: true,
                end_of_utterance: true,
                ..StreamingSttCapabilities::default()
            }
        }

        async fn open_session(
            &self,
            _format: StreamAudioFormat,
            events: mpsc::Sender<StreamingSttEvent>,
        ) -> Result<Box<dyn StreamingSttSession>, SttError> {
            let generation = self.opens.fetch_add(1, Ordering::SeqCst) + 1;
            Ok(Box::new(RecordingSession {
                generation,
                chunks: Arc::clone(&self.chunks),
                events,
            }))
        }
    }

    struct RecordingSession {
        generation: usize,
        chunks: Arc<Mutex<Vec<Vec<u8>>>>,
        events: mpsc::Sender<StreamingSttEvent>,
    }

    struct RestartFailProvider {
        opens: Arc<AtomicUsize>,
    }

    struct PushFailProvider;

    struct PushFailSession;

    #[async_trait]
    impl StreamingSttProvider for PushFailProvider {
        fn id(&self) -> &str {
            "push-fail"
        }

        fn capabilities(&self) -> StreamingSttCapabilities {
            StreamingSttCapabilities::default()
        }

        async fn open_session(
            &self,
            _format: StreamAudioFormat,
            _events: mpsc::Sender<StreamingSttEvent>,
        ) -> Result<Box<dyn StreamingSttSession>, SttError> {
            Ok(Box::new(PushFailSession))
        }
    }

    #[async_trait]
    impl StreamingSttSession for PushFailSession {
        async fn push_audio(&self, _chunk: AudioChunk) -> Result<(), SttError> {
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
            Err(SttError::Transport("push failed".to_string()))
        }

        async fn finish(&self) -> Result<(), SttError> {
            Ok(())
        }
    }

    #[async_trait]
    impl StreamingSttProvider for RestartFailProvider {
        fn id(&self) -> &str {
            "restart-fail"
        }

        fn capabilities(&self) -> StreamingSttCapabilities {
            StreamingSttCapabilities {
                partial_results: true,
                ..StreamingSttCapabilities::default()
            }
        }

        async fn open_session(
            &self,
            _format: StreamAudioFormat,
            events: mpsc::Sender<StreamingSttEvent>,
        ) -> Result<Box<dyn StreamingSttSession>, SttError> {
            let generation = self.opens.fetch_add(1, Ordering::SeqCst) + 1;
            if generation > 1 {
                return Err(SttError::Transport("restart unavailable".to_string()));
            }
            Ok(Box::new(RecordingSession {
                generation,
                chunks: Arc::new(Mutex::new(Vec::new())),
                events,
            }))
        }
    }

    #[async_trait]
    impl StreamingSttSession for RecordingSession {
        async fn push_audio(&self, chunk: AudioChunk) -> Result<(), SttError> {
            self.chunks.lock().await.push(chunk.pcm.to_vec());
            let _ = self
                .events
                .send(StreamingSttEvent::Partial {
                    text: format!("partial-{}", self.generation),
                    speaker: None,
                })
                .await;
            Ok(())
        }

        async fn finish(&self) -> Result<(), SttError> {
            let _ = self
                .events
                .send(StreamingSttEvent::Final {
                    text: format!("final-{}", self.generation),
                    speaker: None,
                    language: Some("en".to_string()),
                    start_ms: None,
                })
                .await;
            Ok(())
        }
    }

    #[tokio::test]
    async fn audio_commit_reopens_and_preserves_event_order() {
        let opens = Arc::new(AtomicUsize::new(0));
        let chunks = Arc::new(Mutex::new(Vec::new()));
        let provider = Arc::new(RecordingProvider {
            opens: Arc::clone(&opens),
            chunks: Arc::clone(&chunks),
        });
        let (handle, mut events) = start_with_pipeline(provider, "test-profile".to_string())
            .await
            .expect("start");

        handle.try_push_audio(vec![1, 2]).expect("audio one");
        handle.try_commit().expect("commit");
        handle.try_push_audio(vec![3, 4]).expect("audio two");
        handle.try_commit().expect("commit second turn");
        handle.try_end().expect("end");

        let mut received = Vec::new();
        while received.len() < 6 {
            received.push(
                tokio::time::timeout(std::time::Duration::from_secs(1), events.recv())
                    .await
                    .expect("event timeout")
                    .expect("event channel"),
            );
        }
        assert_eq!(
            received,
            vec![
                LocalRealtimeTranscriptEvent::Partial {
                    text: "partial-1".to_string(),
                    stream_generation: 1,
                },
                LocalRealtimeTranscriptEvent::Final {
                    text: "final-1".to_string(),
                    stream_generation: 1,
                },
                LocalRealtimeTranscriptEvent::CommitReady {
                    stream_generation: 1,
                },
                LocalRealtimeTranscriptEvent::Partial {
                    text: "partial-2".to_string(),
                    stream_generation: 2,
                },
                LocalRealtimeTranscriptEvent::Final {
                    text: "final-2".to_string(),
                    stream_generation: 2,
                },
                LocalRealtimeTranscriptEvent::CommitReady {
                    stream_generation: 2,
                },
            ]
        );
        assert_eq!(opens.load(Ordering::SeqCst), 3);
        assert_eq!(*chunks.lock().await, vec![vec![1, 2], vec![3, 4]]);
        assert_eq!(handle.profile_id(), "test-profile");
    }

    #[tokio::test]
    async fn clear_suppresses_cancelled_generation_final_and_reopens() {
        let provider = Arc::new(RecordingProvider {
            opens: Arc::new(AtomicUsize::new(0)),
            chunks: Arc::new(Mutex::new(Vec::new())),
        });
        let (handle, mut events) = start_with_pipeline(provider, "test-profile".to_string())
            .await
            .expect("start");

        handle.try_push_audio(vec![1, 2]).expect("cancelled audio");
        handle.try_clear().expect("clear");
        handle.try_push_audio(vec![3, 4]).expect("retained audio");
        handle.try_commit().expect("commit retained turn");
        handle.try_end().expect("end");

        let mut received = Vec::new();
        while let Ok(Some(event)) =
            tokio::time::timeout(std::time::Duration::from_millis(100), events.recv()).await
        {
            received.push(event);
        }
        assert!(received.iter().all(|event| !matches!(
            event,
            LocalRealtimeTranscriptEvent::Final {
                stream_generation: 1,
                ..
            }
        )));
        assert!(received.iter().any(|event| matches!(
            event,
            LocalRealtimeTranscriptEvent::Final {
                text,
                stream_generation: 2,
            } if text == "final-2"
        )));
    }

    #[tokio::test]
    async fn restart_failure_does_not_signal_commit_ready_ahead_of_degradation() {
        let provider = Arc::new(RestartFailProvider {
            opens: Arc::new(AtomicUsize::new(0)),
        });
        let (handle, mut events) = start_with_pipeline(provider, "test-profile".to_string())
            .await
            .expect("start");

        handle.try_push_audio(vec![1, 2]).expect("audio");
        handle.try_commit().expect("commit");

        let first = tokio::time::timeout(std::time::Duration::from_secs(1), events.recv())
            .await
            .expect("first event timeout")
            .expect("first event");
        let second = tokio::time::timeout(std::time::Duration::from_secs(1), events.recv())
            .await
            .expect("second event timeout")
            .expect("second event");
        assert!(matches!(
            first,
            LocalRealtimeTranscriptEvent::Partial {
                stream_generation: 1,
                ..
            }
        ));
        assert!(matches!(
            second,
            LocalRealtimeTranscriptEvent::Final {
                stream_generation: 1,
                ..
            }
        ));
        let error = tokio::time::timeout(std::time::Duration::from_secs(1), events.recv())
            .await
            .expect("error timeout")
            .expect("error event");
        assert!(matches!(
            error,
            LocalRealtimeTranscriptEvent::Error {
                stream_generation: 1,
                ..
            }
        ));
    }

    #[tokio::test]
    async fn provider_input_failure_accounts_for_current_and_queued_audio() {
        let (handle, mut events) =
            start_with_pipeline(Arc::new(PushFailProvider), "test-profile".to_string())
                .await
                .expect("start");
        handle.try_push_audio(vec![1, 2]).expect("first audio");
        handle.try_push_audio(vec![3, 4]).expect("queued audio");

        let error = tokio::time::timeout(std::time::Duration::from_secs(1), events.recv())
            .await
            .expect("error timeout")
            .expect("error event");
        assert!(matches!(error, LocalRealtimeTranscriptEvent::Error { .. }));
        let snapshot = handle.queue_snapshot();
        assert_eq!(snapshot.queued_audio_bytes, 0);
        assert_eq!(snapshot.queued_audio_frames, 0);
        assert!(snapshot.high_water_audio_bytes >= 2);
        assert_eq!(snapshot.dropped_audio_frames, 2);
    }

    #[tokio::test]
    async fn end_accounts_for_audio_queued_behind_terminal_command() {
        let provider = Arc::new(RecordingProvider {
            opens: Arc::new(AtomicUsize::new(0)),
            chunks: Arc::new(Mutex::new(Vec::new())),
        });
        let (handle, _events) = start_with_pipeline(provider, "test-profile".to_string())
            .await
            .expect("start");

        handle.try_end().expect("end");
        let late_audio_result = handle.try_push_audio(vec![1, 2, 3, 4]);
        tokio::time::sleep(std::time::Duration::from_millis(20)).await;

        let snapshot = handle.queue_snapshot();
        assert_eq!(snapshot.queued_audio_bytes, 0);
        assert_eq!(snapshot.queued_audio_frames, 0);
        assert_eq!(snapshot.dropped_audio_frames, 1);
        assert!(matches!(
            late_audio_result,
            Ok(()) | Err(LocalRealtimeTranscriptCommandError::Closed)
        ));
    }

    #[test]
    fn bounded_command_queue_reports_overload_and_closure() {
        let (commands, receiver) = mpsc::channel(1);
        let handle = LocalRealtimeTranscriptHandle {
            commands,
            profile_id: Arc::from("test-profile"),
            next_stream_generation: Arc::new(AtomicU64::new(1)),
            suppressed_event_generations: Arc::new(RwLock::new(HashSet::new())),
            queued_audio_bytes: Arc::new(AtomicUsize::new(0)),
            queued_audio_frames: Arc::new(AtomicUsize::new(0)),
            queue_high_water_bytes: Arc::new(AtomicUsize::new(0)),
            dropped_audio_frames: Arc::new(AtomicU64::new(0)),
        };

        handle.try_push_audio(vec![1, 2]).expect("first command");
        assert_eq!(
            handle.try_commit(),
            Err(LocalRealtimeTranscriptCommandError::QueueFull)
        );
        assert_eq!(handle.current_stream_generation(), 1);
        assert_eq!(
            handle.try_clear(),
            Err(LocalRealtimeTranscriptCommandError::QueueFull)
        );
        assert_eq!(handle.current_stream_generation(), 1);
        assert!(handle
            .suppressed_event_generations
            .read()
            .expect("suppressed generations")
            .is_empty());
        assert_eq!(
            handle.try_push_audio(vec![3, 4, 5]),
            Err(LocalRealtimeTranscriptCommandError::QueueFull)
        );
        assert_eq!(
            handle.queue_snapshot(),
            LocalRealtimeTranscriptQueueSnapshot {
                queued_audio_bytes: 2,
                queued_audio_frames: 1,
                high_water_audio_bytes: 2,
                dropped_audio_frames: 1,
            }
        );

        drop(receiver);
        assert_eq!(
            handle.try_end(),
            Err(LocalRealtimeTranscriptCommandError::Closed)
        );
        assert!(handle
            .suppressed_event_generations
            .read()
            .expect("suppressed generations")
            .is_empty());
    }

    #[test]
    fn bounded_command_queue_rejects_audio_above_byte_budget() {
        let (commands, _receiver) = mpsc::channel(1);
        let handle = LocalRealtimeTranscriptHandle {
            commands,
            profile_id: Arc::from("test-profile"),
            next_stream_generation: Arc::new(AtomicU64::new(1)),
            suppressed_event_generations: Arc::new(RwLock::new(HashSet::new())),
            queued_audio_bytes: Arc::new(AtomicUsize::new(0)),
            queued_audio_frames: Arc::new(AtomicUsize::new(0)),
            queue_high_water_bytes: Arc::new(AtomicUsize::new(0)),
            dropped_audio_frames: Arc::new(AtomicU64::new(0)),
        };

        assert_eq!(
            handle.try_push_audio(vec![0; MAX_QUEUED_AUDIO_BYTES + 1]),
            Err(LocalRealtimeTranscriptCommandError::QueueFull)
        );
        assert_eq!(
            handle.queue_snapshot(),
            LocalRealtimeTranscriptQueueSnapshot {
                queued_audio_bytes: 0,
                queued_audio_frames: 0,
                high_water_audio_bytes: 0,
                dropped_audio_frames: 1,
            }
        );
    }
}
