// Generated by scripts/presentation_identity_codegen.py; do not edit.
pub const PRODUCT_NAME: &str = "Magican";
pub const HOST_APP_NAME: &str = "Magican Desktop";
pub const ASSISTANT_FALLBACK_NAME: &str = "Assistant";
