// Generated by scripts/presentation_identity_codegen.py; do not edit.
package ai.magicbeans.magdroid.identity

object ProductIdentity {
    const val productName = "Magican"
    const val hostAppName = "Magican Desktop"
    const val assistantFallbackName = "Assistant"
}
