// Generated by `make app-contract-codegen`; do not edit.
export const APP_DATA_PLANE_COMPONENT_CONTRACT_VERSION = "1.0.0" as const;
export const APP_SUPPORTED_PUBLIC_CONTRACT_VERSION = "1.5.0" as const;
/** @deprecated Use the explicitly named contract-axis version. */
export const APP_CONTRACT_VERSION = APP_DATA_PLANE_COMPONENT_CONTRACT_VERSION;
export const APP_PROTOCOL_VERSION = "1" as const;
export const APP_SCHEMA_DIGEST = "blake3:d82ada41bfe2205a0f1bac83bd9b43874d1b0670cc2988057d02b43ea632d819" as const;
export const APP_FIXTURE_DIGEST = "blake3:677eaf621bd6b5a47150ec6ad0f4e49fb36f5558c2adccbc610a4b5c11e3a78a" as const;

export const APP_CONTRACT_FIXTURES = {
  "action_cancellation_receipt": {
    "generation": 1,
    "idempotency_key": "cancel:fixture:1",
    "protocol_version": "1",
    "requested_at": "2026-01-01T00:00:00Z",
    "run_ref": "run:app-action:fixture_running",
    "status": "cancelling"
  },
  "action_cancellation_request": {
    "expected_generation": 0,
    "idempotency_key": "cancel:fixture:1"
  },
  "action_composition_request": {
    "destination_action_id": "accept_plan",
    "destination_installation_id": "install_contract_destination",
    "idempotency_key": "compose:fixture:1",
    "mapping": [
      {
        "kind": "select",
        "source": "plan",
        "target": "plan"
      }
    ]
  },
  "action_composition_waiting": {
    "chain": {
      "active_destination_action_id": "accept_plan",
      "active_destination_installation_id": "install_contract_destination",
      "active_source_run_ref": "run:app-action:fixture_source",
      "hop_count": 1,
      "hop_index": 0,
      "origin_source_run_ref": "run:app-action:fixture_source"
    },
    "source_run": {
      "action_id": "build_plan",
      "installation_id": "install_contract_source",
      "protocol_version": "1",
      "run_ref": "run:app-action:fixture_source"
    },
    "status": "waiting"
  },
  "action_invocation": {
    "action_id": "shorten_video",
    "action_revision": 2,
    "caller_surface_or_execution_ref": "surface:library:session_9",
    "idempotency_key": "action-key:fixture:shorten-video",
    "input": {
      "content_digest": "blake3:ac97680718d449e87fd041ca0e1103b2995574a28366fb28cab7c95c0a5ccd06",
      "expires_at": "2026-08-14T07:30:00Z",
      "grant_revision": 2,
      "handling_labels": {
        "classification": "personal",
        "model_processing": "local_only",
        "policy_digest": "blake3:f98f30111fa85c533ff074620814a853afa1e7b6715a55df740ab987affa4996",
        "provenance_digest": "blake3:62403b576e4a52499024b60e62fc1e3bedb2ed48dbbcdaac5e12854cecb9ef65"
      },
      "installation_id": "install_reading_room",
      "package_revision_ref": "package:reading_room:1.0.0",
      "produced_at": "2026-08-14T06:30:00Z",
      "protocol_version": "1",
      "schema_revision": 3,
      "scope_binding_ref": "scope_binding_owner_default",
      "source": "user_input",
      "source_refs": [
        {
          "kind": "entity_record",
          "reference": "record:saved_video:video_01",
          "revision": 7
        }
      ],
      "value": {
        "source_url": "https://example.test/watch/42",
        "target_minutes": 8
      },
      "value_schema_ref": "schema:shorten_video_input:v2"
    },
    "protocol_version": "1",
    "requested_result_schema_ref": "schema:shorten_video_result:v2"
  },
  "action_launch": {
    "execution_id": "execution_fixture_1",
    "run_handle": {
      "action_id": "shorten_video",
      "installation_id": "install_contract_fixture",
      "protocol_version": "1",
      "run_ref": "run:app-action:fixture_completed"
    }
  },
  "action_result_completed": {
    "action_id": "shorten_video",
    "mutation_receipt_refs": [
      "mutation:receipt_01"
    ],
    "output": {
      "content_digest": "blake3:7d5b1d7a30969303743795d55a57e69dc28eb451c761ed257f8fdb9744a41bba",
      "expires_at": "2026-08-14T07:30:00Z",
      "grant_revision": 2,
      "handling_labels": {
        "classification": "personal",
        "model_processing": "local_only",
        "policy_digest": "blake3:f98f30111fa85c533ff074620814a853afa1e7b6715a55df740ab987affa4996",
        "provenance_digest": "blake3:62403b576e4a52499024b60e62fc1e3bedb2ed48dbbcdaac5e12854cecb9ef65"
      },
      "installation_id": "install_reading_room",
      "package_revision_ref": "package:reading_room:1.0.0",
      "produced_at": "2026-08-14T06:30:00Z",
      "protocol_version": "1",
      "schema_revision": 3,
      "scope_binding_ref": "scope_binding_owner_default",
      "source": "app_action",
      "source_refs": [
        {
          "kind": "entity_record",
          "reference": "record:saved_video:video_01",
          "revision": 7
        }
      ],
      "value": {
        "artifact_ref": "artifact:video:short_01",
        "duration_seconds": 481
      },
      "value_schema_ref": "schema:shorten_video_result:v2"
    },
    "protocol_version": "1",
    "run_ref": "run:shorten_video:01",
    "status": "completed"
  },
  "action_result_uncertain": {
    "action_id": "publish_clip",
    "error": {
      "code": "external_outcome_uncertain",
      "details": {
        "destination": "https://publisher.example.test"
      },
      "disposition": "outcome_uncertain",
      "message": "The destination accepted the request but did not confirm its final state."
    },
    "external_effect_receipt_refs": [
      "external_receipt:publish_02"
    ],
    "protocol_version": "1",
    "run_ref": "run:publish_clip:02",
    "status": "uncertain"
  },
  "action_run_completed": {
    "execution_id": "execution_fixture_1",
    "protocol_version": "1",
    "result": {
      "action_id": "shorten_video",
      "mutation_receipt_refs": [
        "mutation:receipt_01"
      ],
      "output": {
        "content_digest": "blake3:7d5b1d7a30969303743795d55a57e69dc28eb451c761ed257f8fdb9744a41bba",
        "expires_at": "2026-08-14T07:30:00Z",
        "grant_revision": 2,
        "handling_labels": {
          "classification": "personal",
          "model_processing": "local_only",
          "policy_digest": "blake3:f98f30111fa85c533ff074620814a853afa1e7b6715a55df740ab987affa4996",
          "provenance_digest": "blake3:62403b576e4a52499024b60e62fc1e3bedb2ed48dbbcdaac5e12854cecb9ef65"
        },
        "installation_id": "install_reading_room",
        "package_revision_ref": "package:reading_room:1.0.0",
        "produced_at": "2026-08-14T06:30:00Z",
        "protocol_version": "1",
        "schema_revision": 3,
        "scope_binding_ref": "scope_binding_owner_default",
        "source": "app_action",
        "source_refs": [
          {
            "kind": "entity_record",
            "reference": "record:saved_video:video_01",
            "revision": 7
          }
        ],
        "value": {
          "artifact_ref": "artifact:video:short_01",
          "duration_seconds": 481
        },
        "value_schema_ref": "schema:shorten_video_result:v2"
      },
      "protocol_version": "1",
      "run_ref": "run:app-action:fixture_completed",
      "status": "completed"
    },
    "result_withheld": false,
    "run_handle": {
      "action_id": "shorten_video",
      "installation_id": "install_contract_fixture",
      "protocol_version": "1",
      "run_ref": "run:app-action:fixture_completed"
    },
    "status": "completed",
    "terminal": true
  },
  "action_run_running": {
    "execution_id": "execution_fixture_1",
    "protocol_version": "1",
    "result_withheld": false,
    "run_handle": {
      "action_id": "shorten_video",
      "installation_id": "install_contract_fixture",
      "protocol_version": "1",
      "run_ref": "run:app-action:fixture_completed"
    },
    "status": "running",
    "terminal": false
  },
  "artifact_projection": {
    "content_digest": "blake3:a14d0ce6199e7290e37376a54e0d4a8b65ae3e83c23980f5c04f76d28e9341a4",
    "expires_at": "2026-08-14T07:30:00Z",
    "grant_revision": 2,
    "handling_labels": {
      "classification": "personal",
      "model_processing": "local_only",
      "policy_digest": "blake3:f98f30111fa85c533ff074620814a853afa1e7b6715a55df740ab987affa4996",
      "provenance_digest": "blake3:62403b576e4a52499024b60e62fc1e3bedb2ed48dbbcdaac5e12854cecb9ef65"
    },
    "installation_id": "install_reading_room",
    "package_revision_ref": "package:reading_room:1.0.0",
    "produced_at": "2026-08-14T06:30:00Z",
    "protocol_version": "1",
    "schema_revision": 3,
    "scope_binding_ref": "scope_binding_owner_default",
    "source": "artifact_projection",
    "source_refs": [
      {
        "kind": "entity_record",
        "reference": "record:saved_video:video_01",
        "revision": 7
      }
    ],
    "value": {
      "artifact_ref": "artifact:video:short_01",
      "artifact_revision": 3,
      "byte_len": 24000000,
      "content_digest": "blake3:7fc369680036e1b5dd437b37a8408fbd9c008e97d845939d2e41bca6e0753a71",
      "media_type": "video/mp4",
      "value_schema_ref": "schema:video_clip:v1"
    },
    "value_schema_ref": "schema:artifact_projection:v1"
  },
  "contract_capabilities": {
    "contract_version": "1.5.0",
    "deprecations": [
      {
        "field": "metadata.magician.app_sdk_version",
        "removal_contract_major": null,
        "replacement": "metadata.magician.required_features for compatibility; metadata.magician.generated_by for diagnostics"
      }
    ],
    "json_schema_dialect": "https://json-schema.org/draft/2020-12/schema",
    "limits": {
      "max_collection_items": 256,
      "max_document_bytes": 1048576,
      "max_entity_change_page_rows": 128,
      "max_json_depth": 32,
      "max_json_nodes": 20000,
      "max_page_rows": 200,
      "max_predicate_depth": 16,
      "max_predicate_nodes": 128,
      "max_value_bytes": 262144,
      "max_value_nodes": 8000
    },
    "operation_inventory_digest": "blake3:4de33a2c5a1637e6d54c57ab9b0de814f0c27bfc0b3e9250f184fa8f2c498d16",
    "operations": [
      {
        "auth": "verified_session",
        "errors": [
          "authenticated_app_session_required",
          "stale_authenticated_request"
        ],
        "idempotency": "read_only",
        "method": "GET",
        "operation_id": "contract_capabilities",
        "parameters": [],
        "path": "/contract-capabilities",
        "response_example": "contract_capabilities",
        "response_schema": "AppContractCapabilities",
        "success_statuses": [
          200
        ],
        "summary": "Negotiate the supported Apps public contract."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "unsupported_app_data_media_type",
          "app_data_body_too_large",
          "app_data_body_read_failed",
          "app_data_body_timeout",
          "app_installation_mismatch",
          "app_data_authority_rejected",
          "app_installation_not_found",
          "app_surface_stale",
          "app_data_projection_denied",
          "invalid_app_data_contract",
          "app_data_encoding_failed",
          "app_data_overloaded",
          "app_data_not_found",
          "app_data_cursor_unavailable",
          "app_data_stale",
          "invalid_app_data_cursor",
          "app_data_query_failed",
          "invalid_app_data_query",
          "app_data_limit_exceeded",
          "app_data_cursor_capacity",
          "app_data_keyset_index_required"
        ],
        "idempotency": "read_only",
        "method": "POST",
        "operation_id": "query_data",
        "parameters": [
          {
            "description": "Opaque installation identity in the authenticated owner scope.",
            "location": "path",
            "name": "installation_id",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/installations/{installation_id}/data/query",
        "request_example": "query_request",
        "request_schema": "AppQueryRequest",
        "response_example": "query_page",
        "response_schema": "AppQueryPage",
        "success_statuses": [
          200
        ],
        "summary": "Query admitted records owned by one installation."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "unsupported_app_data_media_type",
          "app_data_body_too_large",
          "app_data_body_read_failed",
          "app_data_body_timeout",
          "app_data_authority_rejected",
          "app_installation_not_found",
          "app_surface_stale",
          "app_data_projection_denied",
          "invalid_app_data_contract",
          "app_data_encoding_failed",
          "app_data_overloaded",
          "app_data_not_found",
          "invalid_app_data_mutation",
          "app_data_conflict",
          "app_data_limit_exceeded",
          "app_data_mutation_failed"
        ],
        "idempotency": "client_keyed",
        "method": "POST",
        "operation_id": "mutate_data",
        "parameters": [
          {
            "description": "Opaque installation identity in the authenticated owner scope.",
            "location": "path",
            "name": "installation_id",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/installations/{installation_id}/data/mutations",
        "request_example": "mutation_command",
        "request_schema": "AppMutationCommand",
        "response_schema": "AppMutationReceipt",
        "success_statuses": [
          200
        ],
        "summary": "Commit an idempotent optimistic mutation batch."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "unsupported_app_data_media_type",
          "app_data_body_too_large",
          "app_data_body_read_failed",
          "app_data_body_timeout",
          "invalid_app_contract",
          "app_workflow_not_found",
          "app_workflow_stale",
          "app_workflow_not_authorized",
          "app_workflow_invalid",
          "app_workflow_failed",
          "app_projection_too_large",
          "app_projection_expired",
          "app_projection_not_authorized",
          "app_projection_store_unavailable"
        ],
        "idempotency": "client_keyed",
        "method": "POST",
        "operation_id": "launch_action",
        "parameters": [
          {
            "description": "Opaque installation identity in the authenticated owner scope.",
            "location": "path",
            "name": "installation_id",
            "required": true,
            "schema_type": "string"
          },
          {
            "description": "Manifest-declared action name.",
            "location": "path",
            "name": "action_id",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/installations/{installation_id}/actions/{action_id}/runs",
        "request_schema": "AppDirectActionRequest",
        "response_example": "action_launch",
        "response_schema": "AppActionLaunchResponse",
        "success_statuses": [
          202
        ],
        "summary": "Launch an admitted action from minimal owner-supplied input."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "app_workflow_not_found",
          "app_workflow_stale",
          "app_workflow_not_authorized",
          "app_workflow_invalid",
          "app_task_runtime_unavailable",
          "app_run_state_invalid",
          "app_run_identity_changed",
          "app_terminal_result_missing",
          "app_workflow_failed"
        ],
        "idempotency": "read_only",
        "method": "GET",
        "operation_id": "get_action_run",
        "parameters": [
          {
            "description": "Opaque logical action-run reference in the canonical run:app-action: namespace; it carries no authority.",
            "location": "path",
            "name": "run_ref",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/action-runs/{run_ref}",
        "response_example": "action_run_completed",
        "response_schema": "AppRunSnapshot",
        "success_statuses": [
          200,
          202
        ],
        "summary": "Read the typed lifecycle and currently disclosable result for a logical run."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "unsupported_app_data_media_type",
          "app_data_body_too_large",
          "app_data_body_read_failed",
          "app_data_body_timeout",
          "invalid_app_action_composition",
          "app_action_composition_not_authorized",
          "app_action_composition_unavailable",
          "app_action_composition_failed",
          "app_workflow_not_found",
          "app_workflow_stale",
          "app_workflow_not_authorized",
          "app_workflow_invalid",
          "app_task_runtime_unavailable",
          "app_workflow_failed"
        ],
        "idempotency": "client_keyed",
        "method": "POST",
        "operation_id": "compose_action_run",
        "parameters": [
          {
            "description": "Opaque logical action-run reference in the canonical run:app-action: namespace; it carries no authority.",
            "location": "path",
            "name": "run_ref",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/action-runs/{run_ref}/compositions",
        "request_example": "action_composition_request",
        "request_schema": "AppActionCompositionRequest",
        "response_example": "action_composition_waiting",
        "response_schema": "AppActionResultComposition",
        "success_statuses": [
          200,
          202
        ],
        "summary": "Map one canonical action result through a bounded reviewed action chain and read cursor-bound progress."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "unsupported_app_action_cancellation_media_type",
          "app_action_cancellation_body_too_large",
          "app_action_cancellation_body_read_failed",
          "app_action_cancellation_body_timeout",
          "invalid_app_action_cancellation",
          "app_workflow_not_found",
          "app_workflow_stale",
          "app_workflow_not_authorized",
          "app_action_not_started",
          "app_action_already_completed",
          "app_action_cancellation_conflict",
          "app_task_runtime_unavailable",
          "app_action_cancellation_failed"
        ],
        "idempotency": "client_keyed",
        "method": "POST",
        "operation_id": "cancel_action_run",
        "parameters": [
          {
            "description": "Opaque logical action-run reference in the canonical run:app-action: namespace; it carries no authority.",
            "location": "path",
            "name": "run_ref",
            "required": true,
            "schema_type": "string"
          }
        ],
        "path": "/action-runs/{run_ref}/cancel",
        "request_example": "action_cancellation_request",
        "request_schema": "AppActionCancellationRequest",
        "response_example": "action_cancellation_receipt",
        "response_schema": "AppActionCancellationReceipt",
        "success_statuses": [
          200,
          202
        ],
        "summary": "Request generation-bound cancellation of one logical action run."
      },
      {
        "auth": "verified_owner_scope",
        "errors": [
          "authenticated_app_session_required",
          "app_scope_mismatch",
          "app_workspace_required",
          "stale_authenticated_request",
          "invalid_authentication_revision",
          "loopback_peer_required",
          "app_authority_rejected",
          "invalid_app_contract",
          "app_surface_not_found",
          "app_surface_stale",
          "app_change_cursor_ahead",
          "invalid_app_change_limit",
          "app_surface_overloaded",
          "app_registry_failed",
          "app_entity_changes_failed"
        ],
        "idempotency": "read_only",
        "method": "GET",
        "operation_id": "read_entity_changes",
        "parameters": [
          {
            "description": "Opaque installation identity in the authenticated owner scope.",
            "location": "path",
            "name": "installation_id",
            "required": true,
            "schema_type": "string"
          },
          {
            "description": "Last applied durable change sequence, or zero for the initial page.",
            "location": "query",
            "minimum": 0,
            "name": "after_change_sequence",
            "required": false,
            "schema_type": "integer"
          },
          {
            "description": "Positive surface revision whose projection is being refreshed.",
            "location": "query",
            "minimum": 1,
            "name": "surface_revision",
            "required": true,
            "schema_type": "integer"
          },
          {
            "default": 64,
            "description": "Bounded page size; the server default is 64 and the maximum is 128.",
            "location": "query",
            "maximum": 128,
            "minimum": 1,
            "name": "limit",
            "required": false,
            "schema_type": "integer"
          }
        ],
        "path": "/installations/{installation_id}/entity-changes",
        "response_schema": "AppEntityChangeBatch",
        "success_statuses": [
          200
        ],
        "summary": "Read a bounded identifier-only durable change page."
      }
    ],
    "schema_version": 1,
    "sdk_compatibility": {
      "generated_by_is_authority": false,
      "policy": "current_contract_only",
      "supported_contract_versions": [
        "1.5.0"
      ]
    },
    "supported_manifest_features": [
      "typed_entities_v1",
      "declarative_views_v1",
      "governed_actions_v1",
      "immutable_dependencies_v1",
      "owner_data_plane_v1",
      "durable_action_runs_v1",
      "contribution_ports_v1",
      "attention_lanes_v1",
      "llm_operations_v1",
      "custom_surfaces_v1",
      "app_widgets_v1",
      "app_behaviors_v1",
      "app_event_behaviors_v1",
      "app_owner_notifications_v1",
      "app_memory_read_v1"
    ],
    "supported_manifest_schema_versions": [
      "1.0"
    ],
    "supported_protocol_versions": [
      "1"
    ]
  },
  "error_stale_revision": {
    "code": "stale_revision",
    "details": {
      "current_revision": 8
    },
    "disposition": "refresh_and_retry",
    "message": "The record changed after this edit began."
  },
  "mutation_command": {
    "atomicity": "all_or_nothing",
    "expected_record_revisions": [
      {
        "entity": "saved_video",
        "record_id": "video_01",
        "revision": 7
      }
    ],
    "expected_schema_revision": 3,
    "idempotency_key": "mutation-key:fixture:create-video",
    "operations": [
      {
        "entity": "saved_video",
        "kind": "create",
        "payload": {
          "source_url": "https://example.test/watch/42",
          "status": "queued",
          "title": "A smaller, clearer film"
        },
        "temporary_id": "new_video"
      },
      {
        "entity": "saved_video",
        "kind": "update",
        "patch": {
          "status": "archived"
        },
        "record_id": "video_01"
      }
    ],
    "protocol_version": "1"
  },
  "query_page": {
    "envelope": {
      "content_digest": "blake3:997af4cd6b74e8510c6944b8d9789df6ec2bd87bfff64524888245c6e34fb123",
      "expires_at": "2026-08-14T07:30:00Z",
      "grant_revision": 2,
      "handling_labels": {
        "classification": "personal",
        "model_processing": "local_only",
        "policy_digest": "blake3:f98f30111fa85c533ff074620814a853afa1e7b6715a55df740ab987affa4996",
        "provenance_digest": "blake3:62403b576e4a52499024b60e62fc1e3bedb2ed48dbbcdaac5e12854cecb9ef65"
      },
      "installation_id": "install_reading_room",
      "package_revision_ref": "package:reading_room:1.0.0",
      "produced_at": "2026-08-14T06:30:00Z",
      "protocol_version": "1",
      "schema_revision": 3,
      "scope_binding_ref": "scope_binding_owner_default",
      "source": "app_store",
      "source_refs": [
        {
          "kind": "entity_record",
          "reference": "record:saved_video:video_01",
          "revision": 7
        }
      ],
      "value": [
        {
          "entity": "saved_video",
          "fields": {
            "duration_seconds": 1842,
            "status": "ready",
            "title": "The Shape of Useful Time"
          },
          "record_id": "video_01",
          "record_revision": 7
        }
      ],
      "value_schema_ref": "schema:saved_video_projection:v1"
    },
    "next_cursor": "cursor:v1:page_3",
    "result_schema_ref": "schema:saved_video_projection:v1"
  },
  "query_request": {
    "cursor": "cursor:v1:page_2",
    "entity": "saved_video",
    "limit": 25,
    "order": [
      {
        "direction": "descending",
        "field": "created_at"
      }
    ],
    "predicate": {
      "nodes": [
        {
          "field": "duration_seconds",
          "kind": "compare",
          "operator": "greater_than",
          "value": 900
        },
        {
          "field": "status",
          "kind": "in",
          "values": [
            "queued",
            "ready"
          ]
        },
        {
          "children": [
            0,
            1
          ],
          "kind": "all"
        }
      ],
      "root": 2
    },
    "protocol_version": "1",
    "purpose": "library_view",
    "select": [
      "title",
      "duration_seconds",
      "status"
    ],
    "source_installation_id": "install_reading_room"
  }
} as const;

export type AppContractFixtureName = keyof typeof APP_CONTRACT_FIXTURES;
