// Generated by `magician app check --write-generated`; do not edit.
import { defineAppValueCodec, recipeNode } from "@magician/apps";
import type {
AppActionCancellationReceipt, AppActionLaunchResponse, AppArtifactHandle as SdkArtifactHandle,
AppCustomBridgeRunControlRequest, AppEntityHandle as SdkEntityHandle,
AppObservationHandle as SdkObservationHandle, AppOpaqueReference as SdkOpaqueReference,
AppReceiptHandle as SdkReceiptHandle, AppResourceHandle as SdkResourceHandle,
AppRunReference as SdkRunHandle, AppRunSnapshot, AppSessionHandle as SdkSessionHandle,
AppGeneratedValueSchema, AppValueCodec, JsonValue
} from "@magician/apps";

export const APP_CONTRACT_VERSION = "1.0.0" as const;
export const APP_MANIFEST_VERSION = "1.0" as const;
export const APP_TYPESCRIPT_GENERATION_VERSION = 2 as const;
export const APP_REQUIRED_FEATURES = ["governed_actions_v1","durable_action_runs_v1"] as const;
export const APP_GENERATED_BY = {"sdk":"magician-app-authoring","version":"1.0.0"} as const;

export type AppEntityName = "accepted_plan";
export type AppViewName = "accepted_plans";
export type AppWorkflowName = "accept_plan";
export type AppActionName = "accept_plan";

export type AppRunHandle = SdkRunHandle;
export type AppSessionHandle = SdkSessionHandle;
export type AppObservationHandle = SdkObservationHandle;
export type AppArtifactHandle = SdkArtifactHandle;
export type AppReceiptHandle<Kind extends string = string> = SdkReceiptHandle<Kind>;
export type AppResourceHandle<Kind extends string = string> = SdkResourceHandle<Kind>;
export type AppEntityHandle<Entity extends string = string> = SdkEntityHandle<Entity>;

export interface AppEntityAcceptedPlan_35f2f8f9 {
  "accepted": boolean;
  "source_plan_id": string;
}

export type AppWorkflowInputAcceptPlan_51c4fddd = Readonly<{ readonly "source_plan_id": string; }>;
export const AppWorkflowInputSchemaAcceptPlan_51c4fddd = {"version":"v1","root":0,"handling_floor":{"classification":"public","model_processing":"remote_allowed"},"nodes":[{"kind":"record","fields":{"source_plan_id":{"value_type":1,"required":true}}},{"kind":"text","max_bytes":262144}]} as const satisfies AppGeneratedValueSchema;
export const AppWorkflowInputAcceptPlan_51c4fdddCodec: AppValueCodec<AppWorkflowInputAcceptPlan_51c4fddd> = defineAppValueCodec<AppWorkflowInputAcceptPlan_51c4fddd>("workflow-schema:blake3:043e290008a10fc1d3df2c950051898d558821e95bfab27f69709f2bf45650ec", "blake3:043e290008a10fc1d3df2c950051898d558821e95bfab27f69709f2bf45650ec", AppWorkflowInputSchemaAcceptPlan_51c4fddd, "input");

export type AppWorkflowResultAcceptPlan_51c4fddd = Readonly<{ readonly "accepted": boolean; readonly "forward_plan_id": string; }>;
export const AppWorkflowResultSchemaAcceptPlan_51c4fddd = {"version":"v1","root":0,"handling_floor":{"classification":"public","model_processing":"remote_allowed"},"nodes":[{"kind":"record","fields":{"accepted":{"value_type":1,"required":true},"forward_plan_id":{"value_type":2,"required":true}}},{"kind":"boolean"},{"kind":"text","max_bytes":262144}]} as const satisfies AppGeneratedValueSchema;
export const AppWorkflowResultAcceptPlan_51c4fdddCodec: AppValueCodec<AppWorkflowResultAcceptPlan_51c4fddd> = defineAppValueCodec<AppWorkflowResultAcceptPlan_51c4fddd>("workflow-schema:blake3:4b0fc20705a28af66bfb9a319399288456f86dd7a33118b55d651ff5c5fb9543", "blake3:4b0fc20705a28af66bfb9a319399288456f86dd7a33118b55d651ff5c5fb9543", AppWorkflowResultSchemaAcceptPlan_51c4fddd, "result");

export const APP_WORKFLOW_FORMS = {"accept_plan":{"fields":[{"control":"text","name":"source_plan_id","nullable":false,"required":true,"values":null}],"schema_digest":"blake3:043e290008a10fc1d3df2c950051898d558821e95bfab27f69709f2bf45650ec","schema_ref":"workflow-schema:blake3:043e290008a10fc1d3df2c950051898d558821e95bfab27f69709f2bf45650ec"}} as const;
export const APP_LEGACY_UNTYPED_RESULT_WORKFLOWS = [] as const;

export interface AppActionContracts {
  readonly "accept_plan": { readonly workflow: "accept_plan"; readonly input: AppWorkflowInputAcceptPlan_51c4fddd; readonly result: AppWorkflowResultAcceptPlan_51c4fddd };
}
export type AppActionInput<Action extends AppActionName> = AppActionContracts[Action]["input"];
export type AppActionResultValue<Action extends AppActionName> = AppActionContracts[Action]["result"];
export type AppActionLaunch<Action extends AppActionName> = AppActionLaunchResponse<AppActionResultValue<Action>>;

export interface AppCustomSurfaceBridge {
invoke<Action extends AppActionName>(action: Action, input: AppActionInput<Action>): Promise<AppActionLaunch<Action>>;
getRun<Action extends AppActionName>(action: Action, run: AppRunHandle): Promise<AppRunSnapshot<AppActionResultValue<Action>>>;
waitRun<Action extends AppActionName>(action: Action, run: AppRunHandle, maxPolls?: number, pollIntervalMs?: number): Promise<AppRunSnapshot<AppActionResultValue<Action>>>;
cancelRun<Action extends AppActionName>(action: Action, run: AppRunHandle, expectedGeneration: number, idempotencyKey: string): Promise<AppActionCancellationReceipt>;
}
export type AppCustomSurfaceRunControl = AppCustomBridgeRunControlRequest;

/** Exact supported Recipe builder set; no generic/effectful escape hatch is generated. */
export const AppRecipe = Object.freeze({
query: recipeNode.query, get: recipeNode.get, map: recipeNode.map,
validate: recipeNode.validate, emitValue: recipeNode.emitValue,
sequence: recipeNode.sequence, parallel: recipeNode.parallel, switch: recipeNode.switch,
});
