#!/usr/bin/env python3
"""Aggregate `metadata.magician.requires.python_packages` declarations
from every skill's SKILL.md into a single `requirements.txt` at the
skillshub root.

Output is deterministic: alphabetical order, comments noting which
skill(s) require each package. The Makefile `setup-skillshub-python`
target consumes the file via `uv pip install -r requirements.txt`
into a single skillshub-root venv.

Usage:
  python3 skillshub/scripts/aggregate_python_packages.py
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SKILLSHUB = REPO / "skillshub"

# Match `python_packages: ["pkg1", "pkg2"]` on a single line.
_LINE_RE = re.compile(r"python_packages:\s*\[(.*)\]")

# Baseline utilities every Python-using skill / ad-hoc agent script can
# assume are importable. Kept deliberately small — heavy/niche libs
# (pandas, numpy, pyarrow, pytorch, …) should be declared by the skill
# that actually needs them via SKILL.md frontmatter.
BASELINE_PACKAGES: tuple[str, ...] = (
    "PyYAML",  # bootstrap/frontmatter parsing used by setup and materialization
    "python-dotenv",  # ad-hoc .env loading
    "rich",  # pretty terminal output (tables, progress, JSON syntax-highlight)
    "tabulate",  # quick tabular CLI output
)

# These adapters declare their venv-backed interpreter/binary in governed
# `requires.bins`, but the current runtime contract has no python_packages field
# for the generator to read. Keep the build ownership explicit here instead of
# silently deleting working dependencies whenever requirements.txt regenerates.
ADAPTER_PACKAGES: dict[str, tuple[str, ...]] = {
    "beautifulsoup4": ("htmltotext",),
    "certifi": ("meme-generation-via-imgflip",),
    # csvkit ships 13 console scripts (in2csv, csvstat, csvsql, sql2csv, …)
    # that the pack declares in `requires.bins` and builds 26 actions on. It
    # had no setup path of any kind — no target, no requirement, no symlink —
    # so those binaries resolved only from whatever Python happened to sit on
    # the host PATH. On the machine where this was found that was an ad-hoc
    # `/Library/Frameworks/Python.framework/Versions/3.11/`, meaning the pack
    # worked there by accident and every action was dead on a fresh install.
    # Installed into the venv, the dispatcher's `skillshub/.venv/bin` PATH
    # prefix resolves all thirteen with no per-binary wiring.
    "csvkit": ("csvkit",),
    "maigret==0.6.1": ("find-details-by-username",),
    "trafilatura": ("htmltotext",),
    "truststore": ("htmltotext",),
    "yt-dlp": ("youtube-search", "media-fetch"),
}


def parse_skill(skill_md: Path) -> list[str]:
    text = skill_md.read_text()
    m = _LINE_RE.search(text)
    if not m:
        return []
    inner = m.group(1)
    return [p.strip().strip('"').strip("'") for p in inner.split(",") if p.strip()]


def aggregate() -> dict[str, list[str]]:
    """Return {package_name: [skills_requiring_it]}."""
    out: dict[str, list[str]] = defaultdict(list)
    for skill_dir in sorted(SKILLSHUB.iterdir()):
        if not skill_dir.is_dir():
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.is_file():
            continue
        for pkg in parse_skill(skill_md):
            out[pkg].append(skill_dir.name)
    for pkg in BASELINE_PACKAGES:
        out[pkg].append("<baseline>")
    for pkg, skills in ADAPTER_PACKAGES.items():
        out[pkg].extend(skills)
    return out


def render(per_pkg: dict[str, list[str]]) -> str:
    lines = [
        "# Aggregated Python deps for skillshub — generated by",
        "#   skillshub/scripts/aggregate_python_packages.py",
        "# Source: each skill's SKILL.md frontmatter at",
        "#   metadata.magician.requires.python_packages.",
        "# Installed into skillshub/.venv via `make setup-skillshub-python`.",
        "",
    ]
    for pkg in sorted(per_pkg.keys()):
        skills = ", ".join(per_pkg[pkg])
        lines.append(f"# Required by: {skills}")
        lines.append(pkg)
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    per_pkg = aggregate()
    if not per_pkg:
        print("WARN: no skill declared python_packages", file=sys.stderr)
        return 0
    out = SKILLSHUB / "requirements.txt"
    out.write_text(render(per_pkg))
    print(f"wrote {out.relative_to(REPO)} with {len(per_pkg)} unique packages")
    for pkg in sorted(per_pkg.keys()):
        print(f"  - {pkg}  (used by: {', '.join(per_pkg[pkg])})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
