#!/usr/bin/env python3
"""Generate per-skill `.env` files at the deployed runtime location,
populated from the repo-root secrets source.

Skills are split by `skill_layer.py` (in this same dir):
- "system" layer = pure-shell tools / personalities, no secrets needed.
- "scope"  layer = needs API keys / OAuth / interactive auth.

Only scope-layer skills get a `.env` file — they're deployed to
`<scope>/skills/<skill>/config/` (by `make install-scope`). This
script writes `<scope>/skills/<skill>/config/.env` populated with real
values from the repo-root secrets source.

The runtime cli_template dispatcher reads each skill's `config/.env`
at dispatch time (preferring the scope-layer copy when present), so
each skill subprocess only sees its own declared keys.

Source of values:
  $MAGICIAN_ROOT_DIR/operator-config.yaml, else $HOME/MagicianNotes/operator-config.yaml.
  Falls back to the in-tree skillshub/operator-config.yaml for dev checkouts.

Falls back to the legacy `<repo>/.env copy.development` only when no operator
config YAML file is present — emits a deprecation warning when it does.

Idempotent: seeds fresh if missing, fills blanks if existing
(preserves user-edited values).

Usage:
  python3 skillshub/scripts/aggregate_env_examples.py
  python3 skillshub/scripts/aggregate_env_examples.py --scope alice/staging
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make the operator_config helper importable when this script runs as
# `python3 skillshub/scripts/aggregate_env_examples.py` from the repo root.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from operator_config import load_secrets  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
SKILLSHUB = REPO / "skillshub"
DEFAULT_SCOPE = "anonymous/default"


def parse_env_keys(path: Path) -> list[str]:
    """Return env-key names declared in a .env.example (lines like FOO=)."""
    keys: list[str] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key = line.split("=", 1)[0].strip()
        if key and key.replace("_", "").isalnum():
            keys.append(key)
    return keys


def render_env_file(skill_name: str, keys: list[str], values: dict[str, str]) -> str:
    lines = [
        f"# {skill_name} — generated by skillshub/scripts/aggregate_env_examples.py",
        "# Values populated from the repo-root secrets source. Re-run the script",
        "# (or `make -C skillshub setup-env`) to refresh blanks from a newer source.",
        "",
    ]
    for key in keys:
        lines.append(f"{key}={values.get(key, '')}")
    return "\n".join(lines) + "\n"


def _parse_env_kv(path: Path) -> dict[str, str]:
    """Tiny .env-style parser for re-reading scope `.env` files we
    previously wrote. Different concern from `load_secrets()` (which
    reads operator-config.yaml) — this is just for diffing/preserving
    hand edits in the materialized scope file."""
    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        if not key or not key.replace("_", "").isalnum():
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
            value = value[1:-1]
        out[key] = value
    return out


def merge_into_existing(env_path: Path, values: dict[str, str], skill_keys: list[str]) -> int:
    """Fill in missing/empty keys in an existing `.env` from `values`.
    Preserves any non-empty hand-edited values. Source-only keys (not
    in `skill_keys`) are ignored.
    """
    existing = _parse_env_kv(env_path)
    raw = env_path.read_text()
    filled = 0
    new_lines: list[str] = []
    seen_keys: set[str] = set()
    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            new_lines.append(line)
            continue
        key, _, _current = stripped.partition("=")
        key = key.strip()
        seen_keys.add(key)
        if key in values and not existing.get(key, "").strip() and values[key]:
            new_lines.append(f"{key}={values[key]}")
            filled += 1
        else:
            new_lines.append(line)
    appended = [k for k in skill_keys if k not in seen_keys and values.get(k)]
    if appended:
        if new_lines and new_lines[-1].strip():
            new_lines.append("")
        new_lines.append("# Appended for newly-declared skill keys:")
        for key in appended:
            new_lines.append(f"{key}={values[key]}")
            filled += 1
    env_path.write_text("\n".join(new_lines).rstrip() + "\n")
    return filled


def discover_skills_with_env(skills_root: Path) -> list[tuple[str, Path]]:
    """Return [(skill_name, deployed_dir), ...] for skills that have
    a `config/.env.example` at the deployed location."""
    out: list[tuple[str, Path]] = []
    if not skills_root.is_dir():
        return out
    for entry in sorted(skills_root.iterdir()):
        if not entry.is_dir():
            continue
        env_example = entry / "config" / ".env.example"
        if env_example.is_file():
            out.append((entry.name, entry))
    return out


def write_skill_env(
    skill_name: str,
    skill_dir: Path,
    secrets: dict[str, str],
    log: list[str],
) -> int:
    """Write `<skill_dir>/config/.env`. Returns count of populated keys."""
    env_example = skill_dir / "config" / ".env.example"
    keys = parse_env_keys(env_example)
    if not keys:
        log.append(f"  — {skill_name}: .env.example has no keys; skipped")
        return 0
    env_path = skill_dir / "config" / ".env"
    if env_path.exists():
        if not secrets:
            log.append(f"  — {skill_name}: existing .env, no source secrets; left untouched")
            return 0
        filled = merge_into_existing(env_path, secrets, keys)
        if filled:
            log.append(f"  ✓ {skill_name}: filled {filled} blank key(s)")
        else:
            log.append(f"  — {skill_name}: already populated")
        env_path.chmod(0o600)
        return filled
    env_path.write_text(render_env_file(skill_name, keys, secrets))
    env_path.chmod(0o600)
    populated = sum(1 for k in keys if secrets.get(k))
    log.append(f"  ✓ {skill_name}: seeded .env ({populated}/{len(keys)} key(s) populated)")
    return populated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scope", default=DEFAULT_SCOPE,
                        help="<principal>/<workspace> (default: %(default)s)")
    parser.add_argument("--data-root", default=str(REPO / "magician_data_v3"),
                        help="path to magician_data_v3 (default: %(default)s)")
    args = parser.parse_args()

    secrets = load_secrets()
    if secrets:
        print(f"  loaded {len(secrets)} key(s) from operator config")
    else:
        print(
            "  no operator-supplied secrets found "
            "(skillshub/operator-config.yaml absent and no legacy fallback); "
            "env files will be blank"
        )

    data_root = Path(args.data_root)
    scope_skills_root = data_root / "scopes" / args.scope / "skills"
    skills = discover_skills_with_env(scope_skills_root)
    if not skills:
        print(f"  ✗ no scope-layer skills found under {scope_skills_root}")
        print(f"    Run `make -C skillshub install-scope SCOPE={args.scope}` first.")
        return 1

    print(f"== scope:{args.scope} ({scope_skills_root}) ==")
    log: list[str] = []
    total = 0
    for skill_name, skill_dir in skills:
        total += write_skill_env(skill_name, skill_dir, secrets, log)
    for line in log:
        print(line)

    print(f"  done: {total} key(s) populated across {len(skills)} scope-layer skill(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
