//! Minimal taxonomy types and tables for Magician real-time events.
//!
//! This crate exists purely to make `make event-taxonomy-codegen` fast.
//! The `event_taxonomy_dump` binary lives here and only depends on this
//! crate, so it never has to recompile the full `magician` crate.
//!
//! The main `magician` crate re-exports everything here via `pub use`.
//!
//! # Keeping tables in sync
//!
//! `EVENT_TAXONOMY_TABLE` is generated by the `taxonomies!` macro below.
//! The same entry list also lives in `magician/src/magician_v2/realtime_events.rs`
//! to generate `RuntimeTransportEvent::taxonomy_lookup`. When you add a new
//! `RuntimeTransportEvent` variant:
//!
//! 1. Add it to the `taxonomies!` invocation in `realtime_events.rs`
//!    (compiler enforces exhaustiveness on the match arm).
//! 2. Add the same line to the `taxonomies!` invocation below.
//! 3. Run `make event-taxonomy-codegen`.
//!
//! `make event-taxonomy-check` (wired into every build) hashes
//! `realtime_events.rs` + this file + the dump binary source and fails if
//! the TS mirror is stale, so drift is caught before it ships.

use serde::{Deserialize, Serialize};

// ─── Taxonomy types ───────────────────────────────────────────────────────────

/// Operator-meaningful category each event variant belongs to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventCategory {
    Pipeline,
    Plan,
    Tool,
    Slot,
    Clarification,
    Execution,
    Llm,
    Agentic,
    Hitl,
    Agent,
    Task,
    Feed,
    Observability,
    /// Realtime media / capture / TTS / STT / pointer / session lifecycle.
    /// Used by every client surface that participates in the realtime
    /// media rails (web mobile/desktop, tray, extension) for session
    /// registration, capability advertisement, permission state, and
    /// per-channel lifecycle telemetry (`media.tts.*`, `media.capture.*`,
    /// `media.transcript.*`, `media.pointer.*`, `media.artifact.*`).
    Media,
    /// Unified runtime activity — spans opened by the runtime activity
    /// tracing layer across every subsystem (agent steps, background
    /// distillation, classification, memory consolidation, taste
    /// profiling, governed child processes, LLM dispatch) plus the log
    /// lines emitted inside them.
    ///
    /// Deliberately not folded into `Observability`. That category is the
    /// catch-all for unrelated one-off telemetry — heartbeats, alerts,
    /// shell and PTY chunks — so an operator filtering to it would get
    /// the activity stream mixed with everything uncategorised. Activity
    /// is one coherent, high-volume family that the runtime activity view
    /// subscribes to as a whole, which is what the category axis is for.
    ///
    /// Note the adjacent name collision: `ActivityProgress` (this
    /// category) is a log line inside a tracing span, emitted by the
    /// activity layer. `ProgressEvent` (`Observability`) is the bus
    /// envelope carrying a `ProgressMessage` to the progress router.
    /// Different producers, different consumers, unrelated despite the
    /// names.
    Activity,
}

/// Severity of an event from the operator's perspective.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EventSeverity {
    Info,
    Warn,
    Error,
    Decision,
    Attention,
}

/// Per-variant operator metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct EventTaxonomy {
    pub category: EventCategory,
    pub severity: EventSeverity,
    pub user_relevant: bool,
    #[serde(default)]
    pub render: RenderHint,
}

impl EventTaxonomy {
    pub const fn new(
        category: EventCategory,
        severity: EventSeverity,
        user_relevant: bool,
    ) -> Self {
        Self {
            category,
            severity,
            user_relevant,
            render: RenderHint::DEFAULT,
        }
    }

    pub const fn with_render(
        category: EventCategory,
        severity: EventSeverity,
        user_relevant: bool,
        render: RenderHint,
    ) -> Self {
        Self {
            category,
            severity,
            user_relevant,
            render,
        }
    }
}

/// Channel-render hint attached to every event taxonomy row.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct RenderHint {
    #[serde(default)]
    pub chat_kind: ChatRenderKind,
    #[serde(default)]
    pub coalesce_by: CoalesceKey,
}

impl RenderHint {
    pub const DEFAULT: Self = Self {
        chat_kind: ChatRenderKind::Suppress,
        coalesce_by: CoalesceKey::None,
    };

    pub const fn new(chat_kind: ChatRenderKind, coalesce_by: CoalesceKey) -> Self {
        Self {
            chat_kind,
            coalesce_by,
        }
    }
}

/// How the chat timeline renders an event.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum ChatRenderKind {
    #[default]
    Suppress,
    Text,
    TaskCard,
    EscalationCard,
}

/// Which `ProgressMessage` field groups events into the same rendered slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "snake_case")]
pub enum CoalesceKey {
    #[default]
    None,
    ExecutionId,
    TaskId,
    PauseStateId,
}

// ─── RuntimeAgentEventType ───────────────────────────────────────────────────

/// Typed identifiers for GAUI event_types that are not part of
/// `RuntimeTransportEvent` (legacy AGUI lifecycle events, synthetic
/// `chat.*` / `task.*` / `execution.*` keys).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeAgentEventType {
    ReasoningStart,
    ReasoningContent,
    ReasoningEnd,
    ToolCallStarted,
    ToolCallArgs,
    ToolCallFinished,
    ToolResultProjected,
    ToolResultRead,
    PlanSnapshot,
    PlanStepStarted,
    PlanStepFinished,
    AgentCycleFailed,
    AgentCyclePaused,
    AgentGoalCompleted,
    AgentGoalFailed,
    AgentGoalRecovered,
    AgentCircuitOpened,
    AgentCircuitRecovered,
    AgentCreated,
    AgentUpdated,
    AgentDeleted,
    AgentPaused,
    AgentResumed,
    AgentUpdate,
    AgentExecutionMapping,
    AgentFeedbackGenerated,
    AgentFeedbackInjections,
    AgentMemoryReport,
    AgentUiSnapshot,
    AgentUiDelta,
    ChatDelegateStatusChanged,
    /// Fires when the delegated task's output-synthesis pipeline lands
    /// successfully — i.e. `SynthesisReadiness::Ready` reached on the
    /// task state. Distinct from `ChatDelegateStatusChanged`, which
    /// fires when the task reaches *terminal status* (Step 1 of the
    /// v0.6.682 async-synthesis pipeline) but synthesis (Step 2) may
    /// still be running for 5–60s after that. Carries the synthesized
    /// user-output preview + paths so the chat activity card can
    /// render the actual deliverable inline.
    ChatDelegateOutputReady,
    /// Fires when the delegated task's output-synthesis pipeline
    /// exhausted retries — `SynthesisReadiness::Failed`. Carries the
    /// failure stage + last_error + attempts so the activity card can
    /// surface a coral failure pill and a retry affordance pointing
    /// at the existing `POST /retry-synthesis` endpoint.
    ChatDelegateOutputFailed,
    ChatAgentTurnStatusChanged,
    TaskStatusChanged,
    TaskActionProgress,
    TaskChildStatusChanged,
    ExecutionHandedOver,
    RecipeReplayStarted,
    RecipeReplayStepCompleted,
    RecipeReplayStepFailed,
    RecipeReplayAuthHealed,
    RecipeReplayTransportDowngraded,
    RecipeReplayApprovalRequested,
    RecipeReplayApprovalResolved,
    RecipeReplayFallbackHandoff,
    RecipeReplayCompleted,
    RecipeReplayRecompiled,
    /// The stateless loop's per-run outbox evicted records it had already
    /// journalled, and this marker leads the drain that claimed the hole.
    ///
    /// Emitted by `execution::agentic::run_loop::phases::outbox::gap_record`
    /// under the name `OUTBOX_GAP_EVENT`. See the row in
    /// `GAUI_EVENT_TAXONOMY` for why it is `Observability / Warn /
    /// user_relevant = false` and which surfaces that lands it on.
    LoopOutboxGap,
    TutorRunStarted,
    TutorRunCompleted,
    TutorRunFailed,
    TutorStepObserved,
    TutorStepTargetResolved,
    TutorStepDrawing,
    TutorDrawShape,
    TutorStepActionDelegated,
    TutorStepVerifying,
    TutorStepVerified,
    TutorStepFailed,
    TutorStepRecovering,
    TutorStepClearing,
    // Realtime media + control rails (Phase 0–5).
    MediaSessionRegistered,
    MediaSessionUpdated,
    MediaSessionHeartbeat,
    MediaSessionDisconnected,
    MediaSessionRevoked,
    MediaCapabilitiesUpdated,
    MediaPreferencesUpdated,
    UiPreferencesUpdated,
    /// The process-wide chat engine (`chat.harness_engine`) changed; open
    /// composers adopt it. Visible to every scope: it names an engine only.
    ChatEngineUpdated,
    MediaPermissionGranted,
    MediaPermissionDenied,
    MediaPermissionRevoked,
    MediaTtsStarted,
    MediaTtsCompleted,
    MediaTtsCancelled,
    MediaTtsError,
    MediaSttStarted,
    MediaTranscriptDelta,
    MediaTranscriptFinal,
    MediaSttError,
    MediaAudioEngineStarted,
    MediaAudioEngineStopped,
    MediaAudioEngineUnhealthy,
    MediaAudioModelLoading,
    MediaAudioModelLoaded,
    MediaAudioModelUnloaded,
    MediaAudioProfileResolved,
    MediaAudioProfileDegraded,
    MediaAudioVadSpeechStarted,
    MediaAudioVadSpeechEnded,
    MediaAudioProviderFallback,
    MediaAudioFramesDropped,
    MediaVoiceNoteRecordingStarted,
    MediaVoiceNoteRecordingStopped,
    MediaVoiceNoteRecordingFailed,
    MediaVoiceNoteReceived,
    MediaVoiceNoteTranscriptionStarted,
    MediaVoiceNoteTranscriptionCompleted,
    MediaVoiceNoteTranscriptionFailed,
    MediaVoiceNoteTranscribed,
    MediaVoiceNoteChatSubmitStarted,
    MediaVoiceNoteChatSubmitCompleted,
    MediaVoiceNoteChatSubmitFailed,
    MediaVoiceNoteSubmitted,
    MediaVoiceNoteError,
    MediaCaptureStarted,
    MediaCaptureCompleted,
    MediaCaptureCancelled,
    MediaCaptureError,
    MediaPointerCommanded,
    MediaArtifactCreated,
    MediaMascotVisible,
    MediaMascotHidden,
    MediaMascotInvoked,
    MediaMascotBubbleOpened,
    MediaMascotBubbleClosed,
    MediaMascotStateChanged,
    MediaMascotQuietChanged,
    MediaConfigUpdated,
    MediaVoiceSessionMinted,
    MediaVoiceSessionRotated,
    MediaVoiceSurfaceResolved,
    MediaVoiceSessionReconnectAttempt,
    MediaVoiceSessionReconnectFailed,
    MediaVoiceSessionCompaction,
    MediaVoiceLocalTranscriptState,
    MediaVoiceLocalTranscriptQueue,
    MediaVoiceLocalTranscriptTurn,
    MediaVoiceLocalTranscriptFallback,
    MediaVoiceBridgeConnected,
    MediaVoiceBridgeDisconnected,
    MediaVoiceClientMessage,
    MediaVoiceClientAudio,
    MediaVoiceControllerCommand,
    MediaVoiceBridgeError,
    MediaTrayBridgeConnected,
    MediaTrayBridgeDisconnected,
    MediaTrayFrameReceived,
    MediaTrayAudioReceived,
    MediaTrayPointerCommand,
    MediaTrayBridgeError,
}

impl RuntimeAgentEventType {
    pub const ALL: &'static [Self] = &[
        Self::ReasoningStart,
        Self::ReasoningContent,
        Self::ReasoningEnd,
        Self::ToolCallStarted,
        Self::ToolCallArgs,
        Self::ToolCallFinished,
        Self::ToolResultProjected,
        Self::ToolResultRead,
        Self::PlanSnapshot,
        Self::PlanStepStarted,
        Self::PlanStepFinished,
        Self::AgentCycleFailed,
        Self::AgentCyclePaused,
        Self::AgentGoalCompleted,
        Self::AgentGoalFailed,
        Self::AgentGoalRecovered,
        Self::AgentCircuitOpened,
        Self::AgentCircuitRecovered,
        Self::AgentCreated,
        Self::AgentUpdated,
        Self::AgentDeleted,
        Self::AgentPaused,
        Self::AgentResumed,
        Self::AgentUpdate,
        Self::AgentExecutionMapping,
        Self::AgentFeedbackGenerated,
        Self::AgentFeedbackInjections,
        Self::AgentMemoryReport,
        Self::AgentUiSnapshot,
        Self::AgentUiDelta,
        Self::ChatDelegateStatusChanged,
        Self::ChatDelegateOutputReady,
        Self::ChatDelegateOutputFailed,
        Self::ChatAgentTurnStatusChanged,
        Self::TaskStatusChanged,
        Self::TaskActionProgress,
        Self::TaskChildStatusChanged,
        Self::ExecutionHandedOver,
        Self::RecipeReplayStarted,
        Self::RecipeReplayStepCompleted,
        Self::RecipeReplayStepFailed,
        Self::RecipeReplayAuthHealed,
        Self::RecipeReplayTransportDowngraded,
        Self::RecipeReplayApprovalRequested,
        Self::RecipeReplayApprovalResolved,
        Self::RecipeReplayFallbackHandoff,
        Self::RecipeReplayCompleted,
        Self::RecipeReplayRecompiled,
        Self::LoopOutboxGap,
        Self::TutorRunStarted,
        Self::TutorRunCompleted,
        Self::TutorRunFailed,
        Self::TutorStepObserved,
        Self::TutorStepTargetResolved,
        Self::TutorStepDrawing,
        Self::TutorDrawShape,
        Self::TutorStepActionDelegated,
        Self::TutorStepVerifying,
        Self::TutorStepVerified,
        Self::TutorStepFailed,
        Self::TutorStepRecovering,
        Self::TutorStepClearing,
        Self::MediaSessionRegistered,
        Self::MediaSessionUpdated,
        Self::MediaSessionHeartbeat,
        Self::MediaSessionDisconnected,
        Self::MediaSessionRevoked,
        Self::MediaCapabilitiesUpdated,
        Self::MediaPreferencesUpdated,
        Self::UiPreferencesUpdated,
        Self::ChatEngineUpdated,
        Self::MediaPermissionGranted,
        Self::MediaPermissionDenied,
        Self::MediaPermissionRevoked,
        Self::MediaTtsStarted,
        Self::MediaTtsCompleted,
        Self::MediaTtsCancelled,
        Self::MediaTtsError,
        Self::MediaSttStarted,
        Self::MediaTranscriptDelta,
        Self::MediaTranscriptFinal,
        Self::MediaSttError,
        Self::MediaAudioEngineStarted,
        Self::MediaAudioEngineStopped,
        Self::MediaAudioEngineUnhealthy,
        Self::MediaAudioModelLoading,
        Self::MediaAudioModelLoaded,
        Self::MediaAudioModelUnloaded,
        Self::MediaAudioProfileResolved,
        Self::MediaAudioProfileDegraded,
        Self::MediaAudioVadSpeechStarted,
        Self::MediaAudioVadSpeechEnded,
        Self::MediaAudioProviderFallback,
        Self::MediaAudioFramesDropped,
        Self::MediaVoiceNoteRecordingStarted,
        Self::MediaVoiceNoteRecordingStopped,
        Self::MediaVoiceNoteRecordingFailed,
        Self::MediaVoiceNoteReceived,
        Self::MediaVoiceNoteTranscriptionStarted,
        Self::MediaVoiceNoteTranscriptionCompleted,
        Self::MediaVoiceNoteTranscriptionFailed,
        Self::MediaVoiceNoteTranscribed,
        Self::MediaVoiceNoteChatSubmitStarted,
        Self::MediaVoiceNoteChatSubmitCompleted,
        Self::MediaVoiceNoteChatSubmitFailed,
        Self::MediaVoiceNoteSubmitted,
        Self::MediaVoiceNoteError,
        Self::MediaCaptureStarted,
        Self::MediaCaptureCompleted,
        Self::MediaCaptureCancelled,
        Self::MediaCaptureError,
        Self::MediaPointerCommanded,
        Self::MediaArtifactCreated,
        Self::MediaMascotVisible,
        Self::MediaMascotHidden,
        Self::MediaMascotInvoked,
        Self::MediaMascotBubbleOpened,
        Self::MediaMascotBubbleClosed,
        Self::MediaMascotStateChanged,
        Self::MediaMascotQuietChanged,
        Self::MediaConfigUpdated,
        Self::MediaVoiceSessionMinted,
        Self::MediaVoiceSessionRotated,
        Self::MediaVoiceSurfaceResolved,
        Self::MediaVoiceSessionReconnectAttempt,
        Self::MediaVoiceSessionReconnectFailed,
        Self::MediaVoiceSessionCompaction,
        Self::MediaVoiceLocalTranscriptState,
        Self::MediaVoiceLocalTranscriptQueue,
        Self::MediaVoiceLocalTranscriptTurn,
        Self::MediaVoiceLocalTranscriptFallback,
        Self::MediaVoiceBridgeConnected,
        Self::MediaVoiceBridgeDisconnected,
        Self::MediaVoiceClientMessage,
        Self::MediaVoiceClientAudio,
        Self::MediaVoiceControllerCommand,
        Self::MediaVoiceBridgeError,
        Self::MediaTrayBridgeConnected,
        Self::MediaTrayBridgeDisconnected,
        Self::MediaTrayFrameReceived,
        Self::MediaTrayAudioReceived,
        Self::MediaTrayPointerCommand,
        Self::MediaTrayBridgeError,
    ];

    pub fn from_str(event_type: &str) -> Option<Self> {
        Self::ALL
            .iter()
            .find(|variant| variant.as_str() == event_type)
            .copied()
    }

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ReasoningStart => "reasoning.start",
            Self::ReasoningContent => "reasoning.content",
            Self::ReasoningEnd => "reasoning.end",
            Self::ToolCallStarted => "tool.call.started",
            Self::ToolCallArgs => "tool.call.args",
            Self::ToolCallFinished => "tool.call.finished",
            Self::ToolResultProjected => "tool.result.projected",
            Self::ToolResultRead => "tool.result.read",
            Self::PlanSnapshot => "plan.snapshot",
            Self::PlanStepStarted => "plan.step.started",
            Self::PlanStepFinished => "plan.step.finished",
            Self::AgentCycleFailed => "agent.cycle.failed",
            Self::AgentCyclePaused => "agent.cycle.paused",
            Self::AgentGoalCompleted => "agent.goal.completed",
            Self::AgentGoalFailed => "agent.goal.failed",
            Self::AgentGoalRecovered => "agent.goal.recovered",
            Self::AgentCircuitOpened => "agent.circuit.opened",
            Self::AgentCircuitRecovered => "agent.circuit.recovered",
            Self::AgentCreated => "agent.created",
            Self::AgentUpdated => "agent.updated",
            Self::AgentDeleted => "agent.deleted",
            Self::AgentPaused => "agent.paused",
            Self::AgentResumed => "agent.resumed",
            Self::AgentUpdate => "agent.update",
            Self::AgentExecutionMapping => "agent.execution.mapping",
            Self::AgentFeedbackGenerated => "agent.feedback.generated",
            Self::AgentFeedbackInjections => "agent.feedback.injections",
            Self::AgentMemoryReport => "agent.memory.report",
            Self::AgentUiSnapshot => "agent.ui.snapshot",
            Self::AgentUiDelta => "agent.ui.delta",
            Self::ChatDelegateStatusChanged => "chat.delegate.status_changed",
            Self::ChatDelegateOutputReady => "chat.delegate.output_ready",
            Self::ChatDelegateOutputFailed => "chat.delegate.output_failed",
            Self::ChatAgentTurnStatusChanged => "chat.agent_turn.status_changed",
            Self::TaskStatusChanged => "task.status_changed",
            Self::TaskActionProgress => "task.action_progress",
            Self::TaskChildStatusChanged => "task.child.status_changed",
            Self::ExecutionHandedOver => "execution.handed_over",
            Self::RecipeReplayStarted => "recipe.replay.started",
            Self::RecipeReplayStepCompleted => "recipe.replay.step.completed",
            Self::RecipeReplayStepFailed => "recipe.replay.step.failed",
            Self::RecipeReplayAuthHealed => "recipe.replay.auth.healed",
            Self::RecipeReplayTransportDowngraded => "recipe.replay.transport.downgraded",
            Self::RecipeReplayApprovalRequested => "recipe.replay.approval.requested",
            Self::RecipeReplayApprovalResolved => "recipe.replay.approval.resolved",
            Self::RecipeReplayFallbackHandoff => "recipe.replay.fallback.handoff",
            Self::RecipeReplayCompleted => "recipe.replay.completed",
            Self::RecipeReplayRecompiled => "recipe.replay.recompiled",
            Self::LoopOutboxGap => "loop.outbox.gap",
            Self::TutorRunStarted => "tutor.run.started",
            Self::TutorRunCompleted => "tutor.run.completed",
            Self::TutorRunFailed => "tutor.run.failed",
            Self::TutorStepObserved => "tutor.step.observed",
            Self::TutorStepTargetResolved => "tutor.step.target_resolved",
            Self::TutorStepDrawing => "tutor.step.drawing",
            Self::TutorDrawShape => "tutor.draw.shape",
            Self::TutorStepActionDelegated => "tutor.step.action_delegated",
            Self::TutorStepVerifying => "tutor.step.verifying",
            Self::TutorStepVerified => "tutor.step.verified",
            Self::TutorStepFailed => "tutor.step.failed",
            Self::TutorStepRecovering => "tutor.step.recovering",
            Self::TutorStepClearing => "tutor.step.clearing",
            Self::MediaSessionRegistered => "media.session.registered",
            Self::MediaSessionUpdated => "media.session.updated",
            Self::MediaSessionHeartbeat => "media.session.heartbeat",
            Self::MediaSessionDisconnected => "media.session.disconnected",
            Self::MediaSessionRevoked => "media.session.revoked",
            Self::MediaCapabilitiesUpdated => "media.capabilities.updated",
            Self::MediaPreferencesUpdated => "media.preferences.updated",
            Self::UiPreferencesUpdated => "ui.preferences.updated",
            Self::ChatEngineUpdated => "chat.engine.updated",
            Self::MediaPermissionGranted => "media.permission.granted",
            Self::MediaPermissionDenied => "media.permission.denied",
            Self::MediaPermissionRevoked => "media.permission.revoked",
            Self::MediaTtsStarted => "media.tts.started",
            Self::MediaTtsCompleted => "media.tts.completed",
            Self::MediaTtsCancelled => "media.tts.cancelled",
            Self::MediaTtsError => "media.tts.error",
            Self::MediaSttStarted => "media.stt.started",
            Self::MediaTranscriptDelta => "media.transcript.delta",
            Self::MediaTranscriptFinal => "media.transcript.final",
            Self::MediaSttError => "media.stt.error",
            Self::MediaAudioEngineStarted => "media.audio.engine.started",
            Self::MediaAudioEngineStopped => "media.audio.engine.stopped",
            Self::MediaAudioEngineUnhealthy => "media.audio.engine.unhealthy",
            Self::MediaAudioModelLoading => "media.audio.model.loading",
            Self::MediaAudioModelLoaded => "media.audio.model.loaded",
            Self::MediaAudioModelUnloaded => "media.audio.model.unloaded",
            Self::MediaAudioProfileResolved => "media.audio.profile.resolved",
            Self::MediaAudioProfileDegraded => "media.audio.profile.degraded",
            Self::MediaAudioVadSpeechStarted => "media.audio.vad.speech_started",
            Self::MediaAudioVadSpeechEnded => "media.audio.vad.speech_ended",
            Self::MediaAudioProviderFallback => "media.audio.provider.fallback",
            Self::MediaAudioFramesDropped => "media.audio.frames.dropped",
            Self::MediaVoiceNoteRecordingStarted => "media.voice_note.recording_started",
            Self::MediaVoiceNoteRecordingStopped => "media.voice_note.recording_stopped",
            Self::MediaVoiceNoteRecordingFailed => "media.voice_note.recording_failed",
            Self::MediaVoiceNoteReceived => "media.voice_note.received",
            Self::MediaVoiceNoteTranscriptionStarted => "media.voice_note.transcription_started",
            Self::MediaVoiceNoteTranscriptionCompleted => {
                "media.voice_note.transcription_completed"
            },
            Self::MediaVoiceNoteTranscriptionFailed => "media.voice_note.transcription_failed",
            Self::MediaVoiceNoteTranscribed => "media.voice_note.transcribed",
            Self::MediaVoiceNoteChatSubmitStarted => "media.voice_note.chat_submit_started",
            Self::MediaVoiceNoteChatSubmitCompleted => "media.voice_note.chat_submit_completed",
            Self::MediaVoiceNoteChatSubmitFailed => "media.voice_note.chat_submit_failed",
            Self::MediaVoiceNoteSubmitted => "media.voice_note.submitted",
            Self::MediaVoiceNoteError => "media.voice_note.error",
            Self::MediaCaptureStarted => "media.capture.started",
            Self::MediaCaptureCompleted => "media.capture.completed",
            Self::MediaCaptureCancelled => "media.capture.cancelled",
            Self::MediaCaptureError => "media.capture.error",
            Self::MediaPointerCommanded => "media.pointer.commanded",
            Self::MediaArtifactCreated => "media.artifact.created",
            Self::MediaMascotVisible => "media.mascot.visible",
            Self::MediaMascotHidden => "media.mascot.hidden",
            Self::MediaMascotInvoked => "media.mascot.invoked",
            Self::MediaMascotBubbleOpened => "media.mascot.bubble.opened",
            Self::MediaMascotBubbleClosed => "media.mascot.bubble.closed",
            Self::MediaMascotStateChanged => "media.mascot.state.changed",
            Self::MediaMascotQuietChanged => "media.mascot.quiet.changed",
            Self::MediaConfigUpdated => "media.config.updated",
            Self::MediaVoiceSessionMinted => "media.voice.session.minted",
            Self::MediaVoiceSessionRotated => "media.voice.session.rotated",
            Self::MediaVoiceSurfaceResolved => "media.voice.surface.resolved",
            Self::MediaVoiceSessionReconnectAttempt => "media.voice.session.reconnect_attempt",
            Self::MediaVoiceSessionReconnectFailed => "media.voice.session.reconnect_failed",
            Self::MediaVoiceSessionCompaction => "media.voice.session.compaction",
            Self::MediaVoiceLocalTranscriptState => "media.voice.local_transcript.state",
            Self::MediaVoiceLocalTranscriptQueue => "media.voice.local_transcript.queue",
            Self::MediaVoiceLocalTranscriptTurn => "media.voice.local_transcript.turn",
            Self::MediaVoiceLocalTranscriptFallback => "media.voice.local_transcript.fallback",
            Self::MediaVoiceBridgeConnected => "media.voice.bridge.connected",
            Self::MediaVoiceBridgeDisconnected => "media.voice.bridge.disconnected",
            Self::MediaVoiceClientMessage => "media.voice.client_message",
            Self::MediaVoiceClientAudio => "media.voice.client_audio",
            Self::MediaVoiceControllerCommand => "media.voice.controller_command",
            Self::MediaVoiceBridgeError => "media.voice.bridge.error",
            Self::MediaTrayBridgeConnected => "media.tray.bridge.connected",
            Self::MediaTrayBridgeDisconnected => "media.tray.bridge.disconnected",
            Self::MediaTrayFrameReceived => "media.tray.frame.received",
            Self::MediaTrayAudioReceived => "media.tray.audio.received",
            Self::MediaTrayPointerCommand => "media.tray.pointer.command",
            Self::MediaTrayBridgeError => "media.tray.bridge.error",
        }
    }
}

impl std::fmt::Display for RuntimeAgentEventType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

// ─── taxonomy table macro ─────────────────────────────────────────────────────

/// Generates `EVENT_TAXONOMY_TABLE` from the declarative entry list.
///
/// Mirror of the same invocation in `magician/src/magician_v2/realtime_events.rs`
/// which generates `RuntimeTransportEvent::taxonomy_lookup`. Keep both in sync
/// when adding new variants (see crate-level docs).
macro_rules! taxonomies {
    (
        $(
            $variant:ident => ($cat:ident, $sev:ident, $ur:expr)
        ),* $(,)?
    ) => {
        pub const EVENT_TAXONOMY_TABLE: &[(&str, EventTaxonomy)] = &[
            $(
                (
                    stringify!($variant),
                    EventTaxonomy::new(
                        EventCategory::$cat,
                        EventSeverity::$sev,
                        $ur,
                    ),
                ),
            )*
        ];
    };
}

taxonomies! {
    // ─── Pipeline ────────────────────────────────────────────────────
    MessageProcessingStarted => (Pipeline, Info, true),
    QueryAnalysisCompleted => (Pipeline, Info, false),
    StrategySelected => (Pipeline, Decision, true),
    ExplorationProgress => (Pipeline, Info, false),
    MessageCompleted => (Pipeline, Info, true),
    ProcessingError => (Pipeline, Error, true),
    PipelineStarted => (Pipeline, Info, true),
    PipelineStepStarted => (Pipeline, Info, true),
    PipelineStepCompleted => (Pipeline, Info, true),
    PipelineCompleted => (Pipeline, Info, true),
    PipelineFailed => (Pipeline, Error, true),

    // ─── Plan ────────────────────────────────────────────────────────
    AtomicPlanOutlineStarted => (Plan, Info, true),
    AtomicPlanOutlineCompleted => (Plan, Info, true),
    AtomicPlanExpansionStarted => (Plan, Info, false),
    AtomicPlanGenerated => (Plan, Info, true),
    V3PlanningStarted => (Plan, Info, true),
    V3PlanningProgress => (Plan, Info, false),
    V3PlanningCompleted => (Plan, Info, true),
    V3PlanningFailed => (Plan, Error, true),

    // ─── Tool matching ───────────────────────────────────────────────
    ToolMatchingTierStarted => (Tool, Info, false),
    ToolMatchingTierCompleted => (Tool, Info, false),

    // ─── Slot extraction / parameter resolution ──────────────────────
    SlotExtractionStarted => (Slot, Info, false),
    SlotExtracted => (Slot, Info, false),
    SlotEnrichmentStarted => (Slot, Info, false),
    SlotEnrichmentCompleted => (Slot, Info, false),
    SlotConfidenceUpdated => (Slot, Info, false),
    SlotGraphDiff => (Slot, Info, false),
    ClarifiedTaskReady => (Slot, Info, true),
    ParameterInferenceAttempted => (Slot, Info, false),
    ParameterInferred => (Slot, Info, false),
    ParameterInferenceFailed => (Slot, Warn, false),
    ParameterDiscoveryAttempted => (Slot, Info, false),
    ParameterDiscovered => (Slot, Info, false),
    ParameterDiscoveryFailed => (Slot, Warn, false),
    ParameterResolutionProgress => (Slot, Info, false),

    // ─── Clarification (planning HITL) ───────────────────────────────
    ClarificationSessionSnapshot => (Clarification, Info, true),
    ClarificationConfidenceSnapshot => (Clarification, Info, false),
    ClarificationMetricsSnapshot => (Clarification, Info, false),

    // ─── Execution + Workflow lifecycle ──────────────────────────────
    ExecutionStarted => (Execution, Info, true),
    ExecutionStepStarted => (Execution, Info, true),
    ExecutionStepCompleted => (Execution, Info, true),
    ExecutionPaused => (Execution, Warn, true),
    ExecutionResumed => (Execution, Info, true),
    ExecutionFailed => (Execution, Error, true),
    ExecutionCancelled => (Execution, Warn, true),
    ExecutionCompleted => (Execution, Info, true),
    ExecutionInflightResent => (Execution, Info, false),
    ExecutionInflightDropped => (Execution, Warn, false),
    ExecutionRestoreFailed => (Execution, Error, true),
    ExecutionStatusChanged => (Execution, Info, false),
    ExecutionResponsibilityChanged => (Execution, Info, false),
    WorkflowResumed => (Execution, Info, true),
    WorkflowStageResumed => (Execution, Info, false),
    WorkflowResumeFailed => (Execution, Error, true),

    // ─── LLM I/O ─────────────────────────────────────────────────────
    LLMAnalysisStarted => (Llm, Info, false),
    LLMAnalysisCompleted => (Llm, Info, false),
    LLMAnalysisFailed => (Llm, Error, true),
    LLMRequestSent => (Llm, Info, false),
    LLMResponseReceived => (Llm, Info, false),
    InferenceAttempted => (Llm, Info, false),
    ThinkingModeActivated => (Llm, Info, true),
    ThinkingModeCompleted => (Llm, Info, false),

    // ─── Agentic loop ────────────────────────────────────────────────
    AgenticExecutionStarted => (Agentic, Info, true),
    AgenticExecutionCompleted => (Agentic, Info, true),
    AgenticIterationStarted => (Agentic, Info, false),
    AgenticIterationCompleted => (Agentic, Info, false),
    AgenticStepStarted => (Agentic, Info, true),
    AgenticStepCompleted => (Agentic, Info, true),
    AgenticStepFailed => (Agentic, Error, true),
    AgenticStepStuckWarning => (Agentic, Warn, true),
    AgenticPageUnderstanding => (Agentic, Info, false),
    AgenticDecisionMade => (Agentic, Decision, true),
    AgenticActionExecuted => (Agentic, Info, true),
    AgenticClickFallbackUsed => (Agentic, Warn, false),
    AgenticMaxIterationsReached => (Agentic, Warn, true),
    AgenticResumed => (Agentic, Info, true),
    DomChangeDetected => (Agentic, Info, false),
    SubGoalRequested => (Agentic, Decision, true),
    SubGoalOutcome => (Agentic, Info, true),

    // ─── HITL (execution-side AskUser / confirmation) ────────────────
    AgenticWaitingForUser => (Hitl, Attention, true),
    AgenticWaitingForConfirmation => (Hitl, Attention, true),
    HitlRequested => (Hitl, Attention, true),
    HitlResolved => (Hitl, Info, true),
    CriticalRequestAlert => (Hitl, Info, false),
    CriticalRequestRetired => (Hitl, Info, false),
    VerificationRetrievalStatus => (Hitl, Info, true),

    // ─── Agent lifecycle ─────────────────────────────────────────────
    AgentCycleStarted => (Agent, Info, true),
    AgentCycleCompleted => (Agent, Info, true),
    AgentTriggered => (Agent, Info, true),
    AgentEvent => (Agent, Info, false),
    AgentDefinitionChanged => (Agent, Info, true),

    // ─── Task CRUD ───────────────────────────────────────────────────
    TaskCreated => (Task, Info, true),
    TaskUpdated => (Task, Info, false),
    TaskDeleted => (Task, Warn, true),

    // ─── Feed ────────────────────────────────────────────────────────
    FeedItemCreated => (Feed, Info, false),
    FeedItemUpdated => (Feed, Info, false),
    FeedItemRemoved => (Feed, Info, false),
    ExecutionPanelDelta => (Feed, Info, false),

    // ─── Observability (catch-all) ───────────────────────────────────
    Heartbeat => (Observability, Info, false),
    ObservabilityAlert => (Observability, Warn, true),
    ChatMessageReceived => (Observability, Info, true),
    ThinkingMapUpdated => (Observability, Info, false),
    ThinkingMapInterpretProgress => (Observability, Info, false),
    ProgressEvent => (Observability, Info, false),
    ShellOutputChunk => (Observability, Info, false),
    InteractivePtyChunk => (Observability, Info, false),

    // ─── Activity (unified runtime activity spans) ───────────────────
    // Mirror of the same three rows in realtime_events.rs. See the
    // `EventCategory::Activity` doc above for why these are not
    // Observability rows.
    ActivityStarted => (Activity, Info, false),
    ActivityFinished => (Activity, Info, false),
    ActivityProgress => (Activity, Info, false),
    // Cost is a fact about work that already happened, not a condition, so it
    // keeps the family's Info severity. Spend that needs attention is a budget
    // concern with its own events; promoting this would make every priced call
    // look like a problem.
    ActivityCost => (Activity, Info, false),
    DecisionShadowAgreement => (Activity, Info, false),
    DecisionAccountingGap => (Activity, Warn, false),
}

// ─── GAUI taxonomy table ──────────────────────────────────────────────────────

pub const GAUI_EVENT_TAXONOMY: &[(&str, EventTaxonomy)] = &[
    // ─── GAUI canonical events (mirrors ArtifactV2EventType) ──────────

    // Pipeline / message lifecycle
    (
        "message.processing_started",
        EventTaxonomy::new(EventCategory::Pipeline, EventSeverity::Info, true),
    ),
    (
        "query_analysis.completed",
        EventTaxonomy::new(EventCategory::Pipeline, EventSeverity::Info, false),
    ),
    (
        "strategy.selected",
        EventTaxonomy::new(EventCategory::Pipeline, EventSeverity::Info, false),
    ),
    (
        "exploration.progress",
        EventTaxonomy::new(EventCategory::Pipeline, EventSeverity::Info, false),
    ),
    (
        "processing.error",
        EventTaxonomy::new(EventCategory::Observability, EventSeverity::Error, true),
    ),
    // Plan
    (
        "atomic_plan.outline_started",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "atomic_plan.outline_completed",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "atomic_plan.expansion_started",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "atomic_plan.generated",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "plan.created",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, true),
    ),
    (
        "plan.revised",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, true),
    ),
    // Clarification
    (
        "clarification.session_snapshot",
        EventTaxonomy::new(EventCategory::Clarification, EventSeverity::Info, false),
    ),
    (
        "clarification.confidence_snapshot",
        EventTaxonomy::new(EventCategory::Clarification, EventSeverity::Info, false),
    ),
    (
        "clarified_task.ready",
        EventTaxonomy::new(EventCategory::Clarification, EventSeverity::Info, true),
    ),
    // Slot / parameter resolution
    (
        "slot_graph.diff",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "slot_extraction.started",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "slot.extracted",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "slot_enrichment.started",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "slot_enrichment.completed",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "slot.confidence_updated",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "parameter_inference.attempted",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "parameter_inference.inferred",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "parameter_inference.failed",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Warn, false),
    ),
    (
        "parameter_discovery.attempted",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "parameter_discovery.discovered",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Info, false),
    ),
    (
        "parameter_discovery.failed",
        EventTaxonomy::new(EventCategory::Slot, EventSeverity::Warn, false),
    ),
    // Workflow
    (
        "workflow.resumed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "workflow.stage_resumed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "workflow.resume_failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "workflow.stage_started",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "workflow.stage_completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    // LLM I/O
    (
        "llm_analysis.started",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "llm_analysis.completed",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "llm_analysis.failed",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Error, true),
    ),
    (
        "llm.requested",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        // Fires once per LLM call when the first text token arrives
        // through the streaming consumer. Carries `duration_ms` =
        // time-to-first-token. Chat surfaces use this to show TTFT
        // alongside the post-call total duration.
        "llm.first_token",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "llm.succeeded",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "llm.failed",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Error, true),
    ),
    (
        "llm.retry_scheduled",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Warn, false),
    ),
    // Tool matching + execution
    (
        "tool_matching_tier.started",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "tool_matching_tier.completed",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "tool.started",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "tool.succeeded",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, true),
    ),
    (
        "tool.failed",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Error, true),
    ),
    // Agentic loop
    (
        "agentic.execution_started",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, true),
    ),
    (
        "agentic.iteration_started",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, false),
    ),
    (
        "agentic.decision_made",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Decision, false),
    ),
    (
        "agentic.step_stuck_warning",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Warn, true),
    ),
    (
        "agentic.execution_completed",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, true),
    ),
    (
        "agentic.resumed",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, true),
    ),
    (
        "max_iterations_reached",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Warn, true),
    ),
    (
        "sub_goal.requested",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, false),
    ),
    (
        "sub_goal.outcome",
        EventTaxonomy::new(EventCategory::Agentic, EventSeverity::Info, false),
    ),
    // Step lifecycle
    (
        "step.started",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "step.completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "step.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "step.blocked",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Attention, true),
    ),
    (
        "step.skipped",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "step.delegated",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    // HITL inputs (execution-side)
    (
        "input.requested",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Attention, true),
    ),
    (
        "input.received",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Info, true),
    ),
    (
        "input.resolved",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Info, true),
    ),
    (
        "input.promoted_to_task_scope",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Info, false),
    ),
    (
        "waiting_for_confirmation",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Attention, true),
    ),
    // Children + delegation
    (
        "child.spawned",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "child.completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "child.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "child.output_available",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "delegation.launch_authorized",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "delegation.launch_dispatched",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "delegation.launch_failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "delegation.child_linked",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "delegation.child_attach_failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Warn, true),
    ),
    (
        "delegation.results_ready",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "delegation.unmatched_child_dispatched",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Warn, false),
    ),
    (
        "parent.resume_authorized",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "parent.resume_dispatched",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    // Execution lifecycle
    (
        "execution.started",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "execution.runtime_handoff",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.runtime_resume_handoff",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.discovered",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.waiting",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Attention, true),
    ),
    (
        "execution.waiting_on_children",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.waiting_for_user",
        EventTaxonomy::new(EventCategory::Hitl, EventSeverity::Attention, true),
    ),
    (
        "execution.resumed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "execution.outcome_observed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "execution.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "execution.cancelled",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "recipe.cancellation_requested",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "execution.deferred",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.status_changed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.responsibility_changed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution.progress",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution_finalizer.started",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution_finalizer.completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "execution_finalizer.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    // Task finalizers
    (
        "task_agent_finalizer.started",
        EventTaxonomy::new(EventCategory::Task, EventSeverity::Info, false),
    ),
    (
        "task_agent_finalizer.completed",
        EventTaxonomy::new(EventCategory::Task, EventSeverity::Info, false),
    ),
    (
        "task_user_finalizer.started",
        EventTaxonomy::new(EventCategory::Task, EventSeverity::Info, false),
    ),
    (
        "task_user_finalizer.completed",
        EventTaxonomy::new(EventCategory::Task, EventSeverity::Info, false),
    ),
    // Outputs / artifacts / imports / memory
    (
        "output.created",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "output.available",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "output_candidate.proposed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "summary.updated",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "artifact.created",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "artifact.create_failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Error, true),
    ),
    (
        "artifact.referenced",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "artifact.used",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "import.resolved",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "memory.episode_recorded",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    // ─── Legacy AGUI events (still emitted by chat / agent runtime) ───
    (
        "plan.snapshot",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, true),
    ),
    (
        "plan.step.started",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "plan.step.finished",
        EventTaxonomy::new(EventCategory::Plan, EventSeverity::Info, false),
    ),
    (
        "reasoning.start",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "reasoning.content",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "reasoning.end",
        EventTaxonomy::new(EventCategory::Llm, EventSeverity::Info, false),
    ),
    (
        "tool.call.started",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, true),
    ),
    (
        "tool.call.args",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "tool.call.finished",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, true),
    ),
    (
        "tool.result.projected",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "tool.result.read",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, false),
    ),
    (
        "agent.cycle.started",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.cycle.completed",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "hitl.requested",
        EventTaxonomy::with_render(
            EventCategory::Hitl,
            EventSeverity::Warn,
            true,
            // HITL surfaces (AttentionPill / `/attention` / TopBar
            // badge / per-turn RequestActivityCard) already render
            // every pending request; chat doesn't double as a fourth
            // notification surface. See
            // `progress_channels::surface_routing::CHAT_RENDERED_ELSEWHERE`.
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::PauseStateId),
        ),
    ),
    (
        "hitl.resolved",
        EventTaxonomy::with_render(
            EventCategory::Hitl,
            EventSeverity::Info,
            true,
            // Mirror suppress on the resolve side; consumers that need
            // the resolution event still get it through the realtime
            // bus (`pendingHitlStore`, attentionStore feed projection)
            // — chat doesn't need a "resolved" system-message echo.
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::PauseStateId),
        ),
    ),
    (
        // Every verification-controller transition arrives under this one
        // type; the payload's `kind` carries which one
        // (`verification.queued` … `verification.cancelled`). Execution
        // rather than Observability because a gate is what decides whether
        // a coding task completes at all.
        "verification.lifecycle",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        // Canonical Artifact v2 envelope. The transition-specific wire name
        // lives in payload.kind and is catalogued by the rows below.
        "recipe.replay",
        EventTaxonomy::new(EventCategory::Tool, EventSeverity::Info, true),
    ),
    (
        "recipe.replay.started",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.step.completed",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            false,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.step.failed",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Warn,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.auth.healed",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.transport.downgraded",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.approval.requested",
        EventTaxonomy::with_render(
            EventCategory::Hitl,
            EventSeverity::Attention,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.approval.resolved",
        EventTaxonomy::with_render(
            EventCategory::Hitl,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Suppress, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.fallback.handoff",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Warn,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.completed",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "recipe.replay.recompiled",
        EventTaxonomy::with_render(
            EventCategory::Tool,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::ExecutionId),
        ),
    ),
    (
        "agent.cycle.failed",
        EventTaxonomy::with_render(
            EventCategory::Agent,
            EventSeverity::Error,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::None),
        ),
    ),
    (
        "agent.cycle.paused",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Attention, true),
    ),
    (
        "agent.goal.completed",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.goal.failed",
        EventTaxonomy::with_render(
            EventCategory::Agent,
            EventSeverity::Error,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::None),
        ),
    ),
    (
        "agent.goal.recovered",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.circuit.opened",
        EventTaxonomy::with_render(
            EventCategory::Agent,
            EventSeverity::Warn,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::None),
        ),
    ),
    (
        "agent.circuit.recovered",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.created",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.updated",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.deleted",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.paused",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Attention, true),
    ),
    (
        "agent.resumed",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, true),
    ),
    (
        "agent.update",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.execution.mapping",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.feedback.generated",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.feedback.injections",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.memory.report",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.ui.snapshot",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    (
        "agent.ui.delta",
        EventTaxonomy::new(EventCategory::Agent, EventSeverity::Info, false),
    ),
    // ─── Synthetic ProgressMessage event_types ────────────────────────
    // Phase 3.5 — `chat.pack.dispatched` / `chat.pack.progress`
    // entries deleted. Chat-spawned packs now run inside real V3
    // tasks and emit `task.status_changed` (rendered as TaskCard
    // via TaskId coalesce — see entry below).
    (
        "task.status_changed",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    (
        "task.action_progress",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    (
        "task.child.status_changed",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    (
        "execution.handed_over",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    // The stateless loop's per-run outbox is bounded at
    // `MAX_TRACKED_RUNS`, and a run evicted by that cap loses records it
    // had already journalled. Since the projector became the only path
    // from a journalled event to a transport, those are permanently
    // missing events on a live surface. `phases::outbox::gap_record`
    // synthesises this marker at the head of the drain that claims the
    // eviction so the hole is IN the record stream rather than only in a
    // `warn!` line nobody greps.
    //
    // ─── Why Observability / Warn / user_relevant = false ───
    //
    // **Observability**, because that is this taxonomy's existing home
    // for one-off faults and alerts (`processing.error` is already
    // there), and because the alternative that would "route better" is
    // the wrong claim: `Agentic` would suppress the four user-facing
    // surfaces structurally, but this is not agentic-stream content —
    // it is a defect in the transport buffer, and picking a category for
    // its routing side-effects is how the category axis this module is
    // built on stops meaning anything.
    //
    // **Warn**, not Error: records were lost, but the run itself did not
    // fail, and nothing downstream is in an invalid state. Warn is also
    // what makes the marker *findable* — before this row existed
    // `taxonomyFor()` in the TS mirror fell through to the catch-all
    // `observability / info / false`, so a hole was indistinguishable
    // from unclassified noise and invisible to any `severity >= warn`
    // filter on `/events`, in the Internals drawer, and in the runtime
    // Activity view.
    //
    // **`user_relevant = false`**, which is the deliberate render
    // decision and not an oversight. This flag is the operator-vs-user
    // axis: `surface_routing`'s chat, feed, webhook, agent-memory and
    // external-bot predicates all gate on it first. The records this
    // marker is ABOUT — `plan.step.*`, `tool.result.projected`,
    // `reasoning.*` — are themselves `user_relevant = false` and appear
    // only on the operator surfaces. A hole marker that outlived its
    // subject matter into the chat timeline or the user's feed would
    // report an internal buffer defect to somebody who never saw the
    // records and cannot act on the loss. So it renders exactly where
    // the missing records would have rendered: the `/events` NDJSON
    // stream (which now classifies it instead of soft-passing it
    // unrecognised) and every `EventStreamCard` mount over it, at warn
    // prominence.
    //
    // No `with_render`: an explicit `ChatRenderKind::Suppress` is
    // indistinguishable from the default in
    // `surface_routing::chat_render_kind` (step 1 only fires on a
    // non-Suppress hint), and a `CoalesceKey` would be dead on a
    // chat-suppressed event. Stating the decision here beats encoding it
    // as a no-op.
    (
        "loop.outbox.gap",
        EventTaxonomy::new(EventCategory::Observability, EventSeverity::Warn, false),
    ),
    (
        "chat.delegate.status_changed",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::ExecutionId),
        ),
    ),
    // Async output-synthesis pipeline (v0.6.682) completion event —
    // fired by the chat synthesis watcher after the task reaches
    // terminal status AND `SynthesisReadiness::from_task_state`
    // observes `Ready`. Carries `summary_preview` so the activity
    // card morphs its `task::<task_id>` leaf to show the synthesized
    // output. Coalesce by TaskId since the UI keys leaves by task_id.
    (
        "chat.delegate.output_ready",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    // Counterpart to `output_ready`: fired when synthesis exhausted
    // retries (carries `stage` / `last_error` / `attempts` /
    // `failed_at` from the on-disk `SynthesisFailure`) OR when the
    // 5-minute synthesis-phase watcher deadline elapses without ever
    // observing the on-disk marker (`synthetic: true` flag, with
    // `reason: "watcher_timeout"` or `"task_pruned_before_observation"`).
    (
        "chat.delegate.output_failed",
        EventTaxonomy::with_render(
            EventCategory::Execution,
            EventSeverity::Warn,
            true,
            RenderHint::new(ChatRenderKind::TaskCard, CoalesceKey::TaskId),
        ),
    ),
    (
        "chat.agent_turn.status_changed",
        EventTaxonomy::with_render(
            EventCategory::Agent,
            EventSeverity::Info,
            true,
            RenderHint::new(ChatRenderKind::Text, CoalesceKey::None),
        ),
    ),
    // Personal Tutor overlay/HUD lifecycle. These are emitted from the
    // chat turn that owns the tutor run, so the HUD can render a compact
    // observe/draw/act/verify trail while the same events remain visible
    // in `/events` for debugging.
    (
        "tutor.run.started",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "tutor.run.completed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "tutor.run.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Warn, true),
    ),
    (
        "tutor.step.observed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "tutor.step.target_resolved",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "tutor.step.drawing",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "tutor.draw.shape",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "tutor.step.action_delegated",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "tutor.step.verifying",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    (
        "tutor.step.verified",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, true),
    ),
    (
        "tutor.step.failed",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Warn, true),
    ),
    (
        "tutor.step.recovering",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Warn, true),
    ),
    (
        "tutor.step.clearing",
        EventTaxonomy::new(EventCategory::Execution, EventSeverity::Info, false),
    ),
    // ─── Media rails (Phase 0–5 of realtime-media-control-rails) ──────
    // Surface lifecycle: a client surface registers a realtime session,
    // updates capabilities/permissions, and finally disconnects.
    (
        "media.session.registered",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.session.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.session.heartbeat",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.session.disconnected",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.session.revoked",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    (
        "media.capabilities.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.preferences.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "ui.preferences.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "chat.engine.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.permission.granted",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.permission.denied",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    (
        "media.permission.revoked",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // TTS lifecycle (browser-native or provider).
    (
        "media.tts.started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tts.completed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tts.cancelled",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tts.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // STT / transcription lifecycle (provider streams).
    (
        "media.stt.started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.transcript.delta",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.transcript.final",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.stt.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // Process-global engine/model lifecycle remains transport telemetry rather
    // than user-scoped progress, while profile/VAD events are request scoped.
    (
        "media.audio.engine.started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.engine.stopped",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.engine.unhealthy",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    (
        "media.audio.model.loading",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.model.loaded",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.model.unloaded",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    // Resolved audio profiles and VAD-gated streaming diagnostics. Payloads
    // contain provider IDs, boundaries, and aggregate frame counts only.
    (
        "media.audio.profile.resolved",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.profile.degraded",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    (
        "media.audio.vad.speech_started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.vad.speech_ended",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.audio.provider.fallback",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    (
        "media.audio.frames.dropped",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    // Backend-owned voice-note lifecycle.
    (
        "media.voice_note.recording_started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice_note.recording_stopped",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice_note.recording_failed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    (
        "media.voice_note.received",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice_note.transcription_started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice_note.transcription_completed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.voice_note.transcription_failed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    (
        "media.voice_note.transcribed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.voice_note.chat_submit_started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice_note.chat_submit_completed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.voice_note.chat_submit_failed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    (
        "media.voice_note.submitted",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.voice_note.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // Capture lifecycle (camera, mic, screen).
    (
        "media.capture.started",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.capture.completed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.capture.cancelled",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.capture.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // Pointer / overlay (tray surfaces) and artifact attachment.
    (
        "media.pointer.commanded",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.artifact.created",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    // Mascot / presence surface lifecycle.
    (
        "media.mascot.visible",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.mascot.hidden",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.mascot.invoked",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.mascot.bubble.opened",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.mascot.bubble.closed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.mascot.state.changed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.mascot.quiet.changed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    // Media configuration changes are consumed by clients as an invalidation
    // signal. They matter to operators, but are not conversational content.
    (
        "media.config.updated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    // Long-lived voice-session lifecycle. Normal rotation, compaction, and
    // resolved boundaries are operator telemetry; an exhausted reconnect is an
    // operator-visible warning. None is conversational content.
    (
        "media.voice.session.minted",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.session.rotated",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.surface.resolved",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.session.reconnect_attempt",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.session.reconnect_failed",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    (
        "media.voice.session.compaction",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    // Local transcript telemetry is content-free operator evidence. Queue
    // pressure and provider fallback are warnings; ordinary state/turn
    // lifecycle remains informational. None is conversational content.
    (
        "media.voice.local_transcript.state",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.local_transcript.queue",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    (
        "media.voice.local_transcript.turn",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.local_transcript.fallback",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, false),
    ),
    // Realtime voice bridge (Phase 4).
    (
        "media.voice.bridge.connected",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.bridge.disconnected",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.client_message",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.client_audio",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.voice.controller_command",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.voice.bridge.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
    // Tray bridge (Phase 5).
    (
        "media.tray.bridge.connected",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tray.bridge.disconnected",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tray.frame.received",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tray.audio.received",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, false),
    ),
    (
        "media.tray.pointer.command",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Info, true),
    ),
    (
        "media.tray.bridge.error",
        EventTaxonomy::new(EventCategory::Media, EventSeverity::Warn, true),
    ),
];

// ─── Lookup helper ────────────────────────────────────────────────────────────

pub fn lookup_agent_event_taxonomy(event_type: &str) -> Option<EventTaxonomy> {
    use std::sync::OnceLock;
    static INDEX: OnceLock<std::collections::HashMap<&'static str, EventTaxonomy>> =
        OnceLock::new();
    let index = INDEX.get_or_init(|| {
        let mut map: std::collections::HashMap<&'static str, EventTaxonomy> = GAUI_EVENT_TAXONOMY
            .iter()
            .map(|(name, taxonomy)| (*name, *taxonomy))
            .collect();
        for (name, taxonomy) in EVENT_TAXONOMY_TABLE.iter() {
            map.insert(*name, *taxonomy);
        }
        map
    });
    index.get(event_type).copied()
}
