// Generated by `magician app check --write-generated`; do not edit.
import { defineAppValueCodec, recipeNode } from "@magician/apps";
import type {
AppActionCancellationReceipt, AppActionLaunchResponse, AppArtifactHandle as SdkArtifactHandle,
AppCustomBridgeRunControlRequest, AppEntityHandle as SdkEntityHandle,
AppObservationHandle as SdkObservationHandle, AppOpaqueReference as SdkOpaqueReference,
AppReceiptHandle as SdkReceiptHandle, AppResourceHandle as SdkResourceHandle,
AppRunReference as SdkRunHandle, AppRunSnapshot, AppSessionHandle as SdkSessionHandle,
AppGeneratedValueSchema, AppValueCodec, JsonValue
} from "@magician/apps";

export const APP_CONTRACT_VERSION = "1.0.0" as const;
export const APP_MANIFEST_VERSION = "1.0" as const;
export const APP_TYPESCRIPT_GENERATION_VERSION = 2 as const;
export const APP_REQUIRED_FEATURES = ["typed_entities_v1","declarative_views_v1","governed_actions_v1","immutable_dependencies_v1","owner_data_plane_v1","durable_action_runs_v1","custom_surfaces_v1","app_widgets_v1"] as const;
export const APP_GENERATED_BY = {"sdk":"magician_app_cli","version":"1.0.0"} as const;

export type AppEntityName = "thinking_map_snapshot" | "thinking_map_summary";
export type AppViewName = "library";
export type AppWorkflowName = "sync_maps";
export type AppActionName = "sync_maps";

export type AppRunHandle = SdkRunHandle;
export type AppSessionHandle = SdkSessionHandle;
export type AppObservationHandle = SdkObservationHandle;
export type AppArtifactHandle = SdkArtifactHandle;
export type AppReceiptHandle<Kind extends string = string> = SdkReceiptHandle<Kind>;
export type AppResourceHandle<Kind extends string = string> = SdkResourceHandle<Kind>;
export type AppEntityHandle<Entity extends string = string> = SdkEntityHandle<Entity>;

export interface AppEntityThinkingMapSnapshot_1adfd35b {
  "lifecycle": "active" | "paused" | "archived" | "deleted";
  "map_id": string;
  "revision": number;
  "snapshot": string;
  "synced_at": string;
  "title": string;
}

export interface AppEntityThinkingMapSummary_025fdad4 {
  "latest_revision": number;
  "lifecycle": "active" | "paused" | "archived" | "deleted";
  "map_id": string;
  "synced_at": string;
  "title": string;
  "updated_at": string;
}

export type AppWorkflowInputSyncMaps_3adb0ce5 = Readonly<{ readonly "lifecycle"?: "active" | "archived" | "deleted" | "paused"; readonly "limit"?: number; readonly "map_id"?: string; }>;
export const AppWorkflowInputSchemaSyncMaps_3adb0ce5 = {"version":"v1","root":0,"handling_floor":{"classification":"public","model_processing":"remote_allowed"},"nodes":[{"kind":"record","fields":{"lifecycle":{"value_type":1,"required":false},"limit":{"value_type":2,"required":false},"map_id":{"value_type":3,"required":false}}},{"kind":"enum","values":["active","archived","deleted","paused"]},{"kind":"integer"},{"kind":"text","max_bytes":262144}]} as const satisfies AppGeneratedValueSchema;
export const AppWorkflowInputSyncMaps_3adb0ce5Codec: AppValueCodec<AppWorkflowInputSyncMaps_3adb0ce5> = defineAppValueCodec<AppWorkflowInputSyncMaps_3adb0ce5>("workflow-schema:blake3:8e5206801e6cca7ae75145936d9f3bc262f1a0a338161f47805f8b424de4edd1", "blake3:8e5206801e6cca7ae75145936d9f3bc262f1a0a338161f47805f8b424de4edd1", AppWorkflowInputSchemaSyncMaps_3adb0ce5, "input");

export type AppWorkflowResultSyncMaps_3adb0ce5 = Readonly<{ readonly "change_sequence": (Readonly<{ readonly "first": number; readonly "last": number; }>) | null; readonly "committed_record_revisions": ReadonlyArray<Readonly<{ readonly "entity": string; readonly "record_id": string; readonly "revision": number; }>>; readonly "receipt_ref": (string) | null; readonly "summary": (string) | null; }>;
export const AppWorkflowResultSchemaSyncMaps_3adb0ce5 = {"version":"v1","root":0,"handling_floor":{"classification":"personal","model_processing":"remote_allowed"},"nodes":[{"kind":"record","fields":{"change_sequence":{"value_type":1,"required":true},"committed_record_revisions":{"value_type":4,"required":true},"receipt_ref":{"value_type":8,"required":true},"summary":{"value_type":9,"required":true}}},{"kind":"nullable","value_type":2},{"kind":"record","fields":{"first":{"value_type":3,"required":true},"last":{"value_type":3,"required":true}}},{"kind":"integer"},{"kind":"array","items":5,"min_items":0,"max_items":256},{"kind":"record","fields":{"entity":{"value_type":6,"required":true},"record_id":{"value_type":7,"required":true},"revision":{"value_type":3,"required":true}}},{"kind":"text","max_bytes":128},{"kind":"text","max_bytes":255},{"kind":"nullable","value_type":7},{"kind":"nullable","value_type":10},{"kind":"text","max_bytes":4096}]} as const satisfies AppGeneratedValueSchema;
export const AppWorkflowResultSyncMaps_3adb0ce5Codec: AppValueCodec<AppWorkflowResultSyncMaps_3adb0ce5> = defineAppValueCodec<AppWorkflowResultSyncMaps_3adb0ce5>("workflow-schema:blake3:5070b8d4dce0ed7f006b9dc1cf90d201afca187a17d6e348a4c85095592fdb36", "blake3:5070b8d4dce0ed7f006b9dc1cf90d201afca187a17d6e348a4c85095592fdb36", AppWorkflowResultSchemaSyncMaps_3adb0ce5, "result");

export const APP_WORKFLOW_FORMS = {"sync_maps":{"fields":[{"control":"select","name":"lifecycle","nullable":false,"required":false,"values":["active","archived","deleted","paused"]},{"control":"number","name":"limit","nullable":false,"required":false,"values":null},{"control":"text","name":"map_id","nullable":false,"required":false,"values":null}],"schema_digest":"blake3:8e5206801e6cca7ae75145936d9f3bc262f1a0a338161f47805f8b424de4edd1","schema_ref":"workflow-schema:blake3:8e5206801e6cca7ae75145936d9f3bc262f1a0a338161f47805f8b424de4edd1"}} as const;
export const APP_LEGACY_UNTYPED_RESULT_WORKFLOWS = [] as const;

export interface AppActionContracts {
  readonly "sync_maps": { readonly workflow: "sync_maps"; readonly input: AppWorkflowInputSyncMaps_3adb0ce5; readonly result: AppWorkflowResultSyncMaps_3adb0ce5 };
}
export type AppActionInput<Action extends AppActionName> = AppActionContracts[Action]["input"];
export type AppActionResultValue<Action extends AppActionName> = AppActionContracts[Action]["result"];
export type AppActionLaunch<Action extends AppActionName> = AppActionLaunchResponse<AppActionResultValue<Action>>;

export interface AppCustomSurfaceBridge {
invoke<Action extends AppActionName>(action: Action, input: AppActionInput<Action>): Promise<AppActionLaunch<Action>>;
getRun<Action extends AppActionName>(action: Action, run: AppRunHandle): Promise<AppRunSnapshot<AppActionResultValue<Action>>>;
waitRun<Action extends AppActionName>(action: Action, run: AppRunHandle, maxPolls?: number, pollIntervalMs?: number): Promise<AppRunSnapshot<AppActionResultValue<Action>>>;
cancelRun<Action extends AppActionName>(action: Action, run: AppRunHandle, expectedGeneration: number, idempotencyKey: string): Promise<AppActionCancellationReceipt>;
}
export type AppCustomSurfaceRunControl = AppCustomBridgeRunControlRequest;

/** Exact supported Recipe builder set; no generic/effectful escape hatch is generated. */
export const AppRecipe = Object.freeze({
query: recipeNode.query, get: recipeNode.get, map: recipeNode.map,
validate: recipeNode.validate, emitValue: recipeNode.emitValue,
sequence: recipeNode.sequence, parallel: recipeNode.parallel, switch: recipeNode.switch, reconcile: recipeNode.reconcile,
});
