//! Autonomous discovery service
//!
//! Implements Phase 2.2: Autonomous Discovery using LLM-guided tool execution.
//!
//! **Discovery Flow:**
//! 1. Analyze parameter discoverability
//! 2. Generate discovery plan using LLM (browser/bash/curl)
//! 3. Evaluate safety with LLM (SAFE/CONDITIONAL/UNSAFE)
//! 4. Execute safe discovery actions
//! 5. Extract results from tool outputs using LLM
//!
//! **Safety:** All discovery actions are evaluated by LLM for safety before execution.
//! Only read-only, non-destructive operations are executed automatically.

use crate::magician_v2::elicitation::{
    manager::ElicitationError,
    orchestrator_trait::AutonomousDiscoveryService,
    types::{DiscoveryMethod, DiscoveryResult, ParameterContext},
};
use crate::magician_v2::execution::actions::BashAction;
use crate::magician_v2::execution::native_executors::execute_bash_action;
use crate::magician_v2::prompt_identity::render_prompt_identity_section;
use crate::magician_v2::prompts::{
    constants::{names, versions},
    manager::PromptManager,
};
use crate::magician_v2::query_analysis::operation_llm_router::{LLMOperation, OperationLlmRouter};
use crate::magician_v2::strategy::plan::UnresolvedInput;
use async_trait::async_trait;
use runtime_core::ShellSandboxConfig;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tracing::{debug, info, warn};

/// Discovery action plan generated by LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
struct DiscoveryPlan {
    /// Can this parameter be discovered?
    can_discover: bool,

    /// Discovery method to use
    method: DiscoveryMethod,

    /// Command or action to execute
    command: String,

    /// Reasoning for this plan
    reasoning: String,

    /// Expected confidence if successful
    expected_confidence: f64,
}

/// Extraction result from LLM or fast-path analysis
struct ExtractionResult {
    value: Option<serde_json::Value>,
    confidence: f64,
    explanation: String,
}

/// Safety evaluation result from LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
struct SafetyEvaluation {
    /// Safety decision
    #[serde(rename = "decision")]
    is_safe: SafetyDecision,

    /// Risk level (0-10, where 0 = no risk, 10 = extremely dangerous)
    risk_level: u8,

    /// Reasoning for safety decision
    reasoning: String,
}

/// Safety decision classification
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
enum SafetyDecision {
    /// Safe to execute automatically (read-only, no side effects)
    #[serde(rename = "SAFE")]
    Safe,

    /// Requires explicit user confirmation before execution
    #[serde(rename = "CONDITIONAL")]
    Conditional,

    /// Never execute automatically (destructive, privileged)
    #[serde(rename = "UNSAFE")]
    Unsafe,
}

/// Implementation of autonomous discovery service
///
/// Uses LLM to plan and validate safe discovery actions before execution.
///
/// # Not wired, and deliberately not given an attempt identity
///
/// Nothing in production constructs this. The only caller is this file's own
/// test module, and `MagicianServices::with_progressive_elicitation` — the sole
/// setter that could install it — is never called. That is the reason it has no
/// `effect_id`, and the reason threading one in would be the wrong fix: it would
/// add a parameter no caller exists to supply and dress an unreachable path up
/// as a covered one.
///
/// What matters is what wiring it would mean. `discover_parameter` asks a model
/// to author a shell command and then runs it through `execute_bash_action`
/// directly — `curl` included, because the planner emits HTTP as shell text
/// rather than as a structured request. That path does not pass through the
/// loop's dispatch, so every guarantee the effect-identity work establishes is
/// absent from it at once: no attempt id, so a repeat cannot be recognised; no
/// far-side `Idempotency-Key`, so a lost response cannot be deduplicated by the
/// only party able to; no lineage record, so an operator cannot answer "did it
/// fire" afterwards. `SafetyDecision` screens the command's *shape*; it says
/// nothing about whether the command already ran once.
///
/// So: if this is ever wired, it needs a dispatch path, not a parameter. Route
/// discovery execution through the same primitive dispatch every other outward
/// act uses, and the identity arrives with it. Until then the honest position is
/// that this rail performs unattributable outward effects and is switched off —
/// which `DiscoveryResult::external_actions_performed` already reports per call.
///
/// See `docs/components/magician/effect-identity.md`.
pub struct AutonomousDiscoveryServiceImpl {
    /// LLM service for planning and safety evaluation
    llm_service: Arc<OperationLlmRouter>,

    /// Prompt manager for template management
    prompt_manager: Arc<PromptManager>,

    /// Maximum retry attempts for LLM calls
    max_retries: u32,

    /// Shell sandbox config for discovery command execution (read-only)
    shell_sandbox: ShellSandboxConfig,
}

impl AutonomousDiscoveryServiceImpl {
    /// Maximum number of retries for LLM calls
    const MAX_RETRIES: u32 = 2;

    /// Create a new discovery service instance
    pub fn new(
        llm_service: Arc<OperationLlmRouter>,
        prompt_manager: Arc<PromptManager>,
        shell_sandbox: ShellSandboxConfig,
    ) -> Self {
        info!("Creating AutonomousDiscoveryService with LLM-guided discovery");
        Self {
            llm_service,
            prompt_manager,
            max_retries: Self::MAX_RETRIES,
            shell_sandbox,
        }
    }

    /// Call LLM with retry logic for transient failures
    async fn call_llm_with_retry(
        &self,
        operation: &LLMOperation,
        system_prompt: Option<&str>,
        prompt: &str,
        param_name: &str,
        operation_type: &str,
    ) -> Result<serde_json::Value, ElicitationError> {
        let mut last_error: Option<String> = None;

        for attempt in 1..=self.max_retries {
            match self
                .llm_service
                .generate_for_operation_with_system(operation, system_prompt, prompt)
                .await
            {
                Ok(response) => {
                    match serde_json::from_str::<serde_json::Value>(&response.content) {
                        Ok(json) => {
                            if attempt > 1 {
                                info!(
                                    "[LLM-RETRY] ✅ {} succeeded for '{}' on attempt {}",
                                    operation_type, param_name, attempt
                                );
                            }
                            return Ok(json);
                        },
                        Err(e) => {
                            last_error = Some(format!("JSON parse error: {}", e));
                            warn!(
                                "[LLM-RETRY] {} for '{}' attempt {}/{}: Invalid JSON response: {}",
                                operation_type, param_name, attempt, self.max_retries, e
                            );

                            if attempt == self.max_retries {
                                return Err(ElicitationError::InvalidFormat(format!(
                                    "LLM returned invalid JSON after {} attempts: {}",
                                    self.max_retries, e
                                )));
                            }

                            tokio::time::sleep(tokio::time::Duration::from_millis(
                                100 * attempt as u64,
                            ))
                            .await;
                        },
                    }
                },
                Err(e) => {
                    last_error = Some(format!("LLM service error: {}", e));
                    warn!(
                        "[LLM-RETRY] {} for '{}' attempt {}/{}: LLM service error: {}",
                        operation_type, param_name, attempt, self.max_retries, e
                    );

                    if attempt == self.max_retries {
                        return Err(ElicitationError::LlmServiceError(format!(
                            "LLM service failed after {} attempts: {}",
                            self.max_retries, e
                        )));
                    }

                    tokio::time::sleep(tokio::time::Duration::from_millis(200 * attempt as u64))
                        .await;
                },
            }
        }

        Err(ElicitationError::LlmServiceError(
            last_error.unwrap_or_else(|| "Unknown error after retries".to_string()),
        ))
    }
}

impl AutonomousDiscoveryServiceImpl {
    /// Evaluate safety of a discovery action using LLM
    async fn llm_evaluate_safety(
        &self,
        plan: &DiscoveryPlan,
        param_name: &str,
    ) -> Result<SafetyEvaluation, ElicitationError> {
        debug!("Evaluating safety for discovery action: {}", plan.command);

        // Build variables for prompt rendering
        let mut variables = HashMap::new();
        variables.insert("method".to_string(), format!("{:?}", plan.method));
        variables.insert("command".to_string(), plan.command.clone());
        variables.insert("parameter_name".to_string(), param_name.to_string());
        variables.insert("context".to_string(), plan.reasoning.clone());

        // Get rendered prompt from PromptManager
        let prompt = self
            .prompt_manager
            .get_rendered_prompt(
                names::DISCOVERY_SAFETY_EVAL,
                versions::DISCOVERY_SAFETY_EVAL,
                variables,
            )
            .await
            .map_err(|e| {
                ElicitationError::LlmServiceError(format!(
                    "Failed to load discovery_safety_eval prompt: {}",
                    e
                ))
            })?;

        // Use ParameterSafetyCheck operation (small) for security evaluation
        match self
            .call_llm_with_retry(
                &LLMOperation::ParameterSafetyCheck,
                None,
                &prompt,
                param_name,
                "SAFETY-EVAL",
            )
            .await
        {
            Ok(json) => {
                let decision_str = json["decision"].as_str().unwrap_or("UNSAFE");
                let is_safe = match decision_str {
                    "SAFE" => SafetyDecision::Safe,
                    "CONDITIONAL" => SafetyDecision::Conditional,
                    _ => SafetyDecision::Unsafe,
                };

                let risk_level = json["risk_level"].as_u64().unwrap_or(10) as u8;
                let reasoning = json["reasoning"]
                    .as_str()
                    .unwrap_or("No reasoning provided")
                    .to_string();

                info!(
                    "[SAFETY-EVAL] ✅ Command '{}' classified as {:?} (risk: {})",
                    plan.command, is_safe, risk_level
                );

                Ok(SafetyEvaluation {
                    is_safe,
                    risk_level,
                    reasoning,
                })
            },
            Err(e) => {
                warn!("[SAFETY-EVAL] Failed to evaluate safety: {}", e);
                // On error, default to UNSAFE for conservative approach
                Ok(SafetyEvaluation {
                    is_safe: SafetyDecision::Unsafe,
                    risk_level: 10,
                    reasoning: format!("Safety evaluation failed: {}", e),
                })
            },
        }
    }

    /// Generate a discovery plan using LLM
    async fn llm_generate_discovery_plan(
        &self,
        input: &UnresolvedInput,
        context: &ParameterContext,
    ) -> Result<Option<DiscoveryPlan>, ElicitationError> {
        debug!(
            "Generating discovery plan for parameter: {}",
            input.parameter
        );

        // Build context information
        let mut context_info = String::new();
        if let Some(tool_meta) = &context.tool_context {
            context_info.push_str(&format!("Tool: {}\n", tool_meta.name));
            context_info.push_str(&format!("Tool Purpose: {}\n", tool_meta.description));
        }

        if !context.slot_context.is_empty() {
            context_info.push_str("\nAlready Known Parameters:\n");
            for (key, value) in &context.slot_context {
                context_info.push_str(&format!("- {}: {}\n", key, value));
            }
        }

        // Build variables for prompt rendering
        let mut variables = HashMap::new();
        variables.insert("parameter_name".to_string(), input.parameter.clone());
        variables.insert("display_name".to_string(), input.display_name.clone());
        variables.insert("description".to_string(), input.prompt.clone());
        variables.insert("user_message".to_string(), context.user_message.clone());
        variables.insert("context_info".to_string(), context_info);

        // Get rendered prompt from PromptManager
        let prompt = self
            .prompt_manager
            .get_rendered_prompt(
                names::DISCOVERY_PLANNING,
                versions::DISCOVERY_PLANNING,
                variables,
            )
            .await
            .map_err(|e| {
                ElicitationError::LlmServiceError(format!(
                    "Failed to load discovery_planning prompt: {}",
                    e
                ))
            })?;

        let mut system_variables = HashMap::new();
        system_variables.insert(
            "identity_section".to_string(),
            render_prompt_identity_section(context.prompt_identity.as_ref(), false),
        );
        let system_prompt = self
            .prompt_manager
            .get_rendered_prompt(
                names::DISCOVERY_PLANNING_SYSTEM,
                versions::DISCOVERY_PLANNING_SYSTEM,
                system_variables,
            )
            .await
            .map_err(|e| {
                ElicitationError::LlmServiceError(format!(
                    "Failed to load discovery_planning_system prompt: {}",
                    e
                ))
            })?;

        // Use ParameterExtraction operation (nano) for discovery planning
        match self
            .call_llm_with_retry(
                &LLMOperation::ParameterExtraction,
                Some(system_prompt.as_str()),
                &prompt,
                &input.parameter,
                "DISCOVERY-PLAN",
            )
            .await
        {
            Ok(json) => {
                let can_discover = json["can_discover"].as_bool().unwrap_or(false);

                if !can_discover {
                    debug!(
                        "[DISCOVERY-PLAN] ⏭️ Cannot discover '{}' autonomously",
                        input.parameter
                    );
                    return Ok(None);
                }

                // Parse discovery method
                let method_str = json["method"].as_str().unwrap_or("ContextAnalysis");
                let method = match method_str {
                    "BashCommand" => DiscoveryMethod::ToolExecution,
                    "CurlRequest" => DiscoveryMethod::APIQuery,
                    _ => DiscoveryMethod::ContextAnalysis,
                };

                let command = json["command"].as_str().unwrap_or("").to_string();
                let reasoning = json["reasoning"].as_str().unwrap_or("").to_string();
                let expected_confidence = json["expected_confidence"].as_f64().unwrap_or(0.7);

                info!(
                    "[DISCOVERY-PLAN] ✅ Plan for '{}': {} (confidence: {:.2})",
                    input.parameter, method_str, expected_confidence
                );

                Ok(Some(DiscoveryPlan {
                    can_discover: true,
                    method,
                    command,
                    reasoning,
                    expected_confidence,
                }))
            },
            Err(e) => {
                warn!(
                    "[DISCOVERY-PLAN] Failed after retries for '{}': {}",
                    input.parameter, e
                );
                Ok(None)
            },
        }
    }

    /// Extract a parameter value from command output.
    ///
    /// Fast path: single clean line outputs are returned directly.
    /// Complex outputs (multi-line, JSON, etc.) use LLM extraction.
    async fn llm_extract_value(
        &self,
        output: &str,
        input: &UnresolvedInput,
        plan: &DiscoveryPlan,
    ) -> Result<ExtractionResult, ElicitationError> {
        let trimmed = output.trim();

        // Empty output means no value discovered
        if trimmed.is_empty() {
            return Ok(ExtractionResult {
                value: None,
                confidence: 0.0,
                explanation: "Command produced no output".to_string(),
            });
        }

        // Fast path: single clean line — use directly without LLM call
        if !trimmed.contains('\n') && trimmed.len() < 500 {
            info!(
                "[DISCOVERY] Fast-path extraction for '{}': {}",
                input.parameter,
                &trimmed[..trimmed.len().min(80)]
            );
            return Ok(ExtractionResult {
                value: Some(serde_json::Value::String(trimmed.to_string())),
                confidence: plan.expected_confidence,
                explanation: format!("Direct extraction from command output: {}", plan.command),
            });
        }

        // Complex output: use LLM extraction
        let expected_type = input.expected_type.as_deref().unwrap_or("string");
        let mut variables = HashMap::new();
        variables.insert("parameter_name".to_string(), input.parameter.clone());
        variables.insert("expected_type".to_string(), expected_type.to_string());
        variables.insert("command".to_string(), plan.command.clone());
        variables.insert("reasoning".to_string(), plan.reasoning.clone());
        // Truncate output to avoid blowing up context (char-boundary safe)
        let truncated_output = if output.len() > 4000 {
            let boundary = output
                .char_indices()
                .take_while(|(i, _)| *i < 4000)
                .last()
                .map_or(0, |(i, c)| i + c.len_utf8());
            format!("{}...[truncated]", &output[..boundary])
        } else {
            output.to_string()
        };
        variables.insert("output".to_string(), truncated_output);

        let prompt = self
            .prompt_manager
            .get_rendered_prompt(
                names::DISCOVERY_RESULT_EXTRACTION,
                versions::DISCOVERY_RESULT_EXTRACTION,
                variables,
            )
            .await
            .map_err(|e| {
                ElicitationError::LlmServiceError(format!(
                    "Failed to load discovery_result_extraction prompt: {}",
                    e
                ))
            })?;

        match self
            .call_llm_with_retry(
                &LLMOperation::DiscoveryExtraction,
                None,
                &prompt,
                &input.parameter,
                "DISCOVERY-EXTRACT",
            )
            .await
        {
            Ok(json) => {
                let value = match &json["value"] {
                    serde_json::Value::Null => None,
                    v => Some(v.clone()),
                };
                let confidence = json["confidence"].as_f64().unwrap_or(0.5);
                let explanation = json["explanation"]
                    .as_str()
                    .unwrap_or("LLM extraction")
                    .to_string();

                info!(
                    "[DISCOVERY] LLM extraction for '{}': confidence={:.2}",
                    input.parameter, confidence
                );

                Ok(ExtractionResult {
                    value,
                    confidence,
                    explanation,
                })
            },
            Err(e) => {
                warn!(
                    "[DISCOVERY] LLM extraction failed for '{}': {}",
                    input.parameter, e
                );
                Ok(ExtractionResult {
                    value: None,
                    confidence: 0.0,
                    explanation: format!("LLM extraction failed: {}", e),
                })
            },
        }
    }
}

#[async_trait]
impl AutonomousDiscoveryService for AutonomousDiscoveryServiceImpl {
    async fn discover(
        &self,
        input: &UnresolvedInput,
        context: &ParameterContext,
    ) -> Result<DiscoveryResult, ElicitationError> {
        info!(
            "[DISCOVERY] Attempting autonomous discovery for parameter: {}",
            input.parameter
        );

        // Step 1: Generate discovery plan using LLM (Task 2.1)
        let plan = match self.llm_generate_discovery_plan(input, context).await? {
            Some(p) => p,
            None => {
                info!(
                    "[DISCOVERY] ⏭️ No discovery plan available for '{}'",
                    input.parameter
                );
                return Ok(DiscoveryResult {
                    value: None,
                    confidence: 0.0,
                    method: DiscoveryMethod::ContextAnalysis,
                    explanation: "Cannot discover autonomously - requires user input".to_string(),
                    external_actions_performed: false,
                });
            },
        };

        // Step 2: Evaluate safety using LLM (Task 2.2)
        let safety = self.llm_evaluate_safety(&plan, &input.parameter).await?;

        if safety.is_safe != SafetyDecision::Safe {
            warn!(
                "[DISCOVERY] ❌ Discovery action not safe for '{}': {:?} (risk: {})",
                input.parameter, safety.is_safe, safety.risk_level
            );
            return Ok(DiscoveryResult {
                value: None,
                confidence: 0.0,
                method: plan.method,
                explanation: format!(
                    "Discovery action deemed {} (risk level: {}): {}",
                    match safety.is_safe {
                        SafetyDecision::Conditional => "requires user confirmation",
                        SafetyDecision::Unsafe => "unsafe",
                        _ => "not safe",
                    },
                    safety.risk_level,
                    safety.reasoning
                ),
                external_actions_performed: false,
            });
        }

        info!(
            "[DISCOVERY] ✅ Discovery plan approved for '{}', executing: {}",
            input.parameter, plan.command
        );

        // Step 3: Execute the approved discovery action
        let execution_output = match plan.method {
            DiscoveryMethod::ToolExecution | DiscoveryMethod::APIQuery => {
                // Both bash commands and curl commands go through execute_bash_action
                // since the LLM generates curl as shell strings, not structured HTTP requests.
                let action = BashAction::new(&plan.command).with_timeout(15);
                match execute_bash_action(&action, &self.shell_sandbox, None, None).await {
                    Ok(result) => result.as_text().unwrap_or("").to_string(),
                    Err(e) => {
                        warn!(
                            "[DISCOVERY] Execution failed for '{}': {}",
                            input.parameter, e
                        );
                        return Ok(DiscoveryResult {
                            value: None,
                            confidence: 0.0,
                            method: plan.method,
                            explanation: format!("Discovery execution failed: {}", e),
                            external_actions_performed: true,
                        });
                    },
                }
            },
            _ => {
                // ContextAnalysis or other methods don't execute external commands
                return Ok(DiscoveryResult {
                    value: None,
                    confidence: 0.0,
                    method: plan.method,
                    explanation: "Discovery method does not support execution".to_string(),
                    external_actions_performed: false,
                });
            },
        };

        // Step 4: Extract discovered value from execution output
        let extracted = self
            .llm_extract_value(&execution_output, input, &plan)
            .await?;

        Ok(DiscoveryResult {
            value: extracted.value,
            confidence: extracted.confidence,
            method: plan.method,
            explanation: extracted.explanation,
            external_actions_performed: true,
        })
    }

    async fn is_safe_to_discover(
        &self,
        input: &UnresolvedInput,
        context: &ParameterContext,
    ) -> Result<bool, ElicitationError> {
        debug!(
            "[DISCOVERY] Safety check for parameter: {}",
            input.parameter
        );

        // Generate discovery plan
        let plan = match self.llm_generate_discovery_plan(input, context).await? {
            Some(p) => p,
            None => {
                debug!("[DISCOVERY] Cannot generate discovery plan - not safe");
                return Ok(false);
            },
        };

        // Evaluate safety
        let safety = self.llm_evaluate_safety(&plan, &input.parameter).await?;

        Ok(safety.is_safe == SafetyDecision::Safe)
    }
}

#[cfg(any(test, feature = "test-fixtures"))]
mod tests {
    use super::*;
    use crate::config::MagicianConfig;
    use crate::magician_v2::prompts::manager::PromptManager;
    use crate::magician_v2::strategy::plan::{
        AskTiming, DiscoveryTiming, InputSource, QuestionPriority,
    };
    use runtime_core::ShellSandboxMode;
    use std::collections::HashMap;

    fn create_test_input() -> UnresolvedInput {
        UnresolvedInput {
            id: "test_param".to_string(),
            parameter: "test_param".to_string(),
            display_name: "Test Parameter".to_string(),
            step_id: Some("step_1".to_string()),
            linked_steps: vec!["step_1".to_string()],
            expected_type: Some("string".to_string()),
            json_schema: None,
            prompt: "Enter test parameter".to_string(),
            required: true,
            notes: None,
            priority: QuestionPriority::PreExecution,
            ask_timing: AskTiming::PreExecution,
            discovery_timing: DiscoveryTiming::PreExecution,
            default_value: None,
            inference_hints: vec![],
            inference_threshold: 0.7,
            auto_fill: None,
            auto_fill_confidence: None,
            source: InputSource::Planner,
            created_at: None,
            updated_at: None,
            status: None,
        }
    }

    fn create_test_context() -> ParameterContext {
        ParameterContext {
            execution_id: "test_thread".to_string(),
            user_message: "test message".to_string(),
            tool_context: None,
            slot_context: HashMap::new(),
            observations: vec![],
            stage: crate::magician_v2::elicitation::types::WorkflowStage::Planning,
            prompt_identity: None,
        }
    }

    async fn create_test_service() -> AutonomousDiscoveryServiceImpl {
        // Create minimal config for testing
        let config = MagicianConfig::default();
        let llm_service = Arc::new(OperationLlmRouter::new(config.router_config().cloned()));

        // Create test prompt storage
        let storage_config = crate::magician_v2::prompts::json_storage::JsonStorageConfig {
            storage_dir: crate::magician_v2::prompts::json_storage::default_prompt_dir(),
            enable_cache: false,
            max_cache_entries: 100,
        };
        let storage = crate::magician_v2::prompts::JsonPromptStorage::new(storage_config).unwrap();
        let prompt_manager = Arc::new(PromptManager::new(Arc::new(storage)));

        let shell_sandbox = ShellSandboxConfig {
            mode: ShellSandboxMode::ReadOnly,
            allow_network: true,
            ..ShellSandboxConfig::default()
        };

        AutonomousDiscoveryServiceImpl::new(llm_service, prompt_manager, shell_sandbox)
    }

    #[tokio::test]
    #[ignore] // Requires actual LLM service configuration with API keys
    async fn test_discovery_with_llm() {
        // This test requires a real LLM service with proper API configuration.
        // To enable this test:
        // 1. Set up OpenAI/Anthropic/Ollama API keys in config
        // 2. Ensure magician-config.yaml has proper LLM configuration
        // 3. Run with: cargo test test_discovery_with_llm -- --ignored --nocapture

        let service = create_test_service().await;
        let input = create_test_input();
        let context = create_test_context();

        let result = service.discover(&input, &context).await;
        assert!(result.is_ok());

        let discovery_result = result.unwrap();
        // LLM discovery should either return a value or explain why it cannot discover
        assert!(!discovery_result.explanation.is_empty());
    }

    #[tokio::test]
    #[ignore] // Requires actual LLM service configuration with API keys
    async fn test_safety_evaluation() {
        let service = create_test_service().await;
        let input = create_test_input();
        let context = create_test_context();

        let result = service.is_safe_to_discover(&input, &context).await;
        assert!(result.is_ok());

        // Safety evaluation should return true/false based on LLM analysis
        // Result depends on whether LLM determines the parameter can be safely discovered
    }
}
